### ISSUE TITLE
Bug: ValueError occurs while trying to read string values from csv files

### ISSUE THREAD

**Issue by syamrajsatheesh** [fhswf/MLPro#1028]
**1 Describe the bug**
While trying to read csv files, if they contain string values, a ValueError is raised.

.../MLPro/MLPro/src/mlpro/bf/streams/streams/csv_file.py", line 203, in _init_dataset
    self._dataset[:,x] = np.array(extended_data[ft_name])
    ~~~~~~~~~~~~~^^^^^
ValueError: could not convert string to float: '10.0.0.17'

**2 To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**3 Expected behavior**
..

**4 Screenshots**
..

**5 Additional Informations**

5.1 Operating System
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by steveyuwono** [comment]
Hi @syamrajsatheesh , I have updated the related source to allow retrieving strings from csv file and pushed them into your branch "oa/streams/cbad". To validate the result, I was using "**howto_bf_streams_002_accessing_data_from_csv_files.py**" by changing line 56 to "**mem.memorize("action",ep_id,"abc")**". Could you test it once again on your implementation? Let me know whether the error remains occur. If everything is fine, I will close this issue.

**Comment by syamrajsatheesh** [comment]
@steveyuwono I tested it. It is now working perfectly fine. You can close this issue. Thank you, Steve.
