### ISSUE TITLE
Refact: Renaming of class bf.systems.Controller

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#1052]
**Motivation**
This class enables access to external sensors and actuators. Since we are to extend MLPro by closed-loop control with controller classes we need to find a better name for this class to avoid name collisions and misunderstandings.

Proposals are:

- SAHub ('Sensor/Actuator-Hub')
- SAGateway ('Sensor/Actuator-Gateway')

**Benefit**
Avoidance of name collisions and misunderstandings.

**Are the proposed changes backward compatible?** 
- [ ] Yes
- [x] No

**Related development objects**
- [x] Class bf.systems.Controller
- [x] Class bf.systems.System
    - [x] Method add_controller 
- [x] Related howtos
- [x] RTD: Update of related class diagram

**Comment by detlefarend** [comment]
Hi @steveyuwono, what do you think? Do you have a better name in mind?

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, what do you think? Do you have a better name in mind?

Hi @detlefarend , SAHub and SAGateway sound nice and catchy. At the moment, I can not find anything better
