### ISSUE TITLE
Paper Elsevier Journal MLWA 2022

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#124]
**Detlef:**
- [x] Title
- [x] Abstract
- [x] 1 Introduction
- [x] 2 Fundamentals of MLPro
- [x] 3 MLPro-RL - The Sub-Framework for Reinforcement Learning
- [x] 6 Conclusion and Future Work

**Steve:**
- [x] 4 MLPro-GT - The Sub-Framework for Game Theory
- [x] 5.a Simulation of a Bulk Goods Plant

**Rizky:**
- [x] 5.b Control of a UR Robot Arm

**Review:**
- [x] Review 1 (all authors)
- [x] Review 2 (Prof. Schwung)

**Submission:**
- [x] Paper submitted (Detlef)

**Journal:**
https://www.journals.elsevier.com/machine-learning-with-applications

**Comment by detlefarend** [comment]
Hi colleagues,

I finished my parts and started reviewing everything. Here are some annotations on my part:

**Section 3: MLPro-RL**
Would be nice if you could review it. Is it correct, logical, understandable? Is something important missing? 

**Section 4: MLPro-GT**
@steveyuwono: have the explanations in Sec.3 an impact to this section?

**Section 5: Sample Apps**
Here are some hints from my perspective that hopefully help to unify and focus the sample sections:
I think we can roughly break down each sample into three parts and the following aspects are rather meaned as a kind of checklist to ensure that we don't forget something: 

a) Description of the scenario
- Environment/Game Board (technical name/rtd url as footnote)
- Agent/Player structure, Policy algorithms (SB3 algo with wrapper, ...)
- Scenario and related Howto if public (technical name/rtd url as footnote). If not public we should annotate the reason.
- Training setup: especially the termination criteria. Here I please you to try the new evaluation strategy with stagnation detection.
- Nice appetizing picture(s)

b) Training results
- Evaluation based plot
- Highscore, Number of training cycles/episodes

c) Summary
What did we demonstrate?

**Subsection 5a: BGLP**
The policy algo is private and as such not part of MLPro. Shall we describe this shortly? 

**Subsection 5b: UR5 Robot**
@rizkydiprasetya: Shall we show both robot pictures (sim/real) side by side? Are you fine with repeating the training with evaluation/stagnation or is there any difficulty (except runtime)?

**Section 6: Conclusion**
Please review and let me know whether we can optimize something.

Thx!!

**Comment by rizkydiprasetya** [comment]
ok. For now only runtime. I will try to run with evaluation/stagnation on environment robothtm.
