### ISSUE TITLE
ReadTheDocs - Introduction

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#148]
TOC

- [x] 1 Introduction
   - [x] 1.1 Key Features
   - [x] 1.2 Architecture
      - [x] 1.2.1 Standardized Machine Learning
      - [x] 1.2.2 Example Pool
      - [x] 1.2.3 Third Party Support
      - [x] 1.2.4 Real-World Applications
   - [x] 1.3 Development
- [x] 2 Getting Started

**Comment by detlefarend** [comment]
Hi @steveyuwono, I have reworked and extended the intro. Could you please check whether there are typos or things to improve? Thank you!

**Comment by steveyuwono** [comment]
> 

Okay, I will check them tomorrow and let you know once it is finished.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the other day, you were trying to out hyperlinks on an image object in sphinx. I found a way...
If you include an attribute ':target:' to your image object, you can link it to external hyperlinks

 %3CmxGraphModel%3E%3Croot%3E%3CmxCell%20id%3D%220%22%2F%3E%3CmxCell%20id%3D%221%22%20parent%3D%220%22%2F%3E%3CmxCell%20id%3D%222%22%20value%3D%22%22%20style%3D%22group%22%20vertex%3D%221%22%20connectable%3D%220%22%20parent%3D%221%22%3E%3CmxGeometry%20x%3D%221160%22%20y%3D%2240%22%20width%3D%22490%22%20height%3D%22220%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%223%22%20value%3D%22%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%20size%3D%26quot%3B1%26quot%3B%26gt%3B%26lt%3Bb%20style%3D%26quot%3Bfont-size%3A%2014px%26quot%3B%26gt%3BLegend%3A%26lt%3Bbr%26gt%3B%26lt%3B%2Fb%26gt%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%230000ff%26quot%3B%20style%3D%26quot%3Bfont-size%3A%206px%26quot%3B%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bspan%20style%3D%26quot%3Bcolor%3A%20rgb(0%20%2C%200%20%2C%200)%26quot%3B%26gt%3B%26lt%3Bfont%20style%3D%26quot%3Bfont-size%3A%204px%26quot%3B%26gt%3B%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%26lt%3B%2Ffont%26gt%3B%26amp%3Bnbsp%3BIn%20progress%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20In%20validation%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3BReady%20to%20use%26lt%3B%2Fspan%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%26gt%3B%26amp%3Bnbsp%3B%26lt%3Bbr%26gt%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%230000ff%26quot%3B%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26amp%3Bnbsp%3Battribute%20%2F%20method()%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20New%20public%20attribute%2Fmethod%20to%20be%20implemented%26lt%3B%2Ffont%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%26gt%3B%26amp%3Bnbsp%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%26gt%3Battribute%20%2F%20method()%26lt%3Bspan%26gt%3B%26%239%3B%26lt%3B%2Fspan%26gt%3B%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3BNew%2Finherited%20public%20attribute%2Fmethod%20that%20is%20implemented%20here%26lt%3Bbr%26gt%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%230000ff%26quot%3B%26gt%3B%26amp%3Bnbsp%3B_attribute%20%2F%26amp%3Bnbsp%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%230000ff%26quot%3B%26gt%3B_method()%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20New%20protected%20method%2Fattribute%20to%20be%20implemented%26lt%3B%2Ffont%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%26gt%3B%26amp%3Bnbsp%3B_attribute%20%2F%20_method()%26amp%3Bnbsp%3B%20%26amp%3Bnbsp%3B%20New%2Finherited%20protected%20attribute%2Fmethod%20that%20is%20implemented%20here%26lt%3Bbr%26gt%3B%26lt%3B%2Ffont%26gt%3B%26lt%3Bfont%20color%3D%26quot%3B%23000000%26quot%3B%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3Bbr%26gt%3B%26lt%3B%2Ffont%26gt%3B%22%20style%3D%22text%3Bhtml%3D1%3Balign%3Dleft%3BverticalAlign%3Dtop%3BwhiteSpace%3Dwrap%3Brounded%3D0%3BfontColor%3D%23006600%3BstrokeColor%3D%23000000%3Bshadow%3D1%3BfillColor%3D%23ffffff%3B%22%20vertex%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20width%3D%22489.99999999999994%22%20height%3D%22220%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%224%22%20value%3D%22Depends%20on%22%20style%3D%22endArrow%3Dblock%3Bhtml%3D1%3BlabelPosition%3Dright%3BverticalLabelPosition%3Dmiddle%3Balign%3Dleft%3BverticalAlign%3Dmiddle%3BendFill%3D1%3BfontSize%3D12%3B%22%20edge%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20x%3D%22-1623.1249999999998%22%20y%3D%22-2180%22%20width%3D%2251.041666666666664%22%20height%3D%2250%22%20as%3D%22geometry%22%3E%3CmxPoint%20x%3D%2210.208023989898948%22%20y%3D%22120.00301587301601%22%20as%3D%22sourcePoint%22%2F%3E%3CmxPoint%20x%3D%2255.990852272727125%22%20y%3D%22120.00301587301601%22%20as%3D%22targetPoint%22%2F%3E%3CmxPoint%20x%3D%2298%22%20as%3D%22offset%22%2F%3E%3CArray%20as%3D%22points%22%3E%3CmxPoint%20x%3D%2230.625%22%20y%3D%22120%22%2F%3E%3C%2FArray%3E%3C%2FmxGeometry%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%225%22%20value%3D%22Inherits%20from%22%20style%3D%22endArrow%3Dblock%3Bhtml%3D1%3BlabelPosition%3Dright%3BverticalLabelPosition%3Dmiddle%3Balign%3Dleft%3BverticalAlign%3Dmiddle%3BendFill%3D0%3BfontSize%3D12%3B%22%20edge%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20x%3D%22-1623.1249999999998%22%20y%3D%22-2180%22%20width%3D%2251.041666666666664%22%20height%3D%2250%22%20as%3D%22geometry%22%3E%3CmxPoint%20x%3D%2210.208023989898948%22%20y%3D%22132.3846031746034%22%20as%3D%22sourcePoint%22%2F%3E%3CmxPoint%20x%3D%2255.990852272727125%22%20y%3D%22132.3846031746034%22%20as%3D%22targetPoint%22%2F%3E%3CmxPoint%20x%3D%2298%22%20y%3D%221%22%20as%3D%22offset%22%2F%3E%3C%2FmxGeometry%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%226%22%20value%3D%22%22%20style%3D%22swimlane%3BfontStyle%3D3%3Balign%3Dcenter%3BverticalAlign%3Dtop%3BchildLayout%3DstackLayout%3Bhorizontal%3D1%3BstartSize%3D26%3BhorizontalStack%3D0%3BresizeParent%3D1%3BresizeLast%3D0%3Bcollapsible%3D1%3BmarginBottom%3D0%3Brounded%3D0%3Bshadow%3D1%3BstrokeWidth%3D1%3BfillColor%3D%23f8cecc%3BstrokeColor%3D%23b85450%3BgradientColor%3D%23ffffff%3BswimlaneFillColor%3D%23ffffff%3B%22%20vertex%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20x%3D%2210.208333333333258%22%20y%3D%2240%22%20width%3D%2240.83333333333333%22%20height%3D%2234%22%20as%3D%22geometry%22%3E%3CmxRectangle%20x%3D%22230%22%20y%3D%22140%22%20width%3D%22160%22%20height%3D%2226%22%20as%3D%22alternateBounds%22%2F%3E%3C%2FmxGeometry%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%227%22%20value%3D%22%22%20style%3D%22line%3Bhtml%3D1%3BstrokeWidth%3D1%3Balign%3Dleft%3BverticalAlign%3Dmiddle%3BspacingTop%3D-1%3BspacingLeft%3D3%3BspacingRight%3D3%3Brotatable%3D0%3BlabelPosition%3Dright%3Bpoints%3D%5B%5D%3BportConstraint%3Deastwest%3B%22%20vertex%3D%221%22%20parent%3D%226%22%3E%3CmxGeometry%20y%3D%2226%22%20width%3D%2240.83333333333333%22%20height%3D%228%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%228%22%20value%3D%22%22%20style%3D%22swimlane%3BfontStyle%3D3%3Balign%3Dcenter%3BverticalAlign%3Dtop%3BchildLayout%3DstackLayout%3Bhorizontal%3D1%3BstartSize%3D26%3BhorizontalStack%3D0%3BresizeParent%3D1%3BresizeLast%3D0%3Bcollapsible%3D1%3BmarginBottom%3D0%3Brounded%3D0%3Bshadow%3D1%3BstrokeWidth%3D1%3BfillColor%3D%23fff2cc%3BstrokeColor%3D%23d6b656%3BgradientColor%3D%23ffffff%3BswimlaneFillColor%3D%23ffffff%3B%22%20vertex%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20x%3D%22112.29166666666674%22%20y%3D%2240%22%20width%3D%2240.83333333333333%22%20height%3D%2234%22%20as%3D%22geometry%22%3E%3CmxRectangle%20x%3D%22230%22%20y%3D%22140%22%20width%3D%22160%22%20height%3D%2226%22%20as%3D%22alternateBounds%22%2F%3E%3C%2FmxGeometry%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%229%22%20value%3D%22%22%20style%3D%22line%3Bhtml%3D1%3BstrokeWidth%3D1%3Balign%3Dleft%3BverticalAlign%3Dmiddle%3BspacingTop%3D-1%3BspacingLeft%3D3%3BspacingRight%3D3%3Brotatable%3D0%3BlabelPosition%3Dright%3Bpoints%3D%5B%5D%3BportConstraint%3Deastwest%3B%22%20vertex%3D%221%22%20parent%3D%228%22%3E%3CmxGeometry%20y%3D%2226%22%20width%3D%2240.83333333333333%22%20height%3D%228%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%2210%22%20value%3D%22%22%20style%3D%22swimlane%3BfontStyle%3D3%3Balign%3Dcenter%3BverticalAlign%3Dtop%3BchildLayout%3DstackLayout%3Bhorizontal%3D1%3BstartSize%3D26%3BhorizontalStack%3D0%3BresizeParent%3D1%3BresizeLast%3D0%3Bcollapsible%3D1%3BmarginBottom%3D0%3Brounded%3D0%3Bshadow%3D1%3BstrokeWidth%3D1%3BfillColor%3D%23dae8fc%3BstrokeColor%3D%236c8ebf%3BgradientColor%3D%23ffffff%3BswimlaneFillColor%3D%23ffffff%3B%22%20vertex%3D%221%22%20parent%3D%222%22%3E%3CmxGeometry%20x%3D%22214.375%22%20y%3D%2240%22%20width%3D%2240.83333333333333%22%20height%3D%2234%22%20as%3D%22geometry%22%3E%3CmxRectangle%20x%3D%22230%22%20y%3D%22140%22%20width%3D%22160%22%20height%3D%2226%22%20as%3D%22alternateBounds%22%2F%3E%3C%2FmxGeometry%3E%3C%2FmxCell%3E%3CmxCell%20id%3D%2211%22%20value%3D%22%22%20style%3D%22line%3Bhtml%3D1%3BstrokeWidth%3D1%3Balign%3Dleft%3BverticalAlign%3Dmiddle%3BspacingTop%3D-1%3BspacingLeft%3D3%3BspacingRight%3D3%3Brotatable%3D0%3BlabelPosition%3Dright%3Bpoints%3D%5B%5D%3BportConstraint%3Deastwest%3B%22%20vertex%3D%221%22%20parent%3D%2210%22%3E%3CmxGeometry%20y%3D%2226%22%20width%3D%2240.83333333333333%22%20height%3D%228%22%20as%3D%22geometry%22%2F%3E%3C%2FmxCell%3E%3C%2Froot%3E%3C%2FmxGraphModel%3E

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, thanks for the hint. I was actually able to solve it in the same way. By the way: start page and intro is done. Would be cool if you could take a look and give me a feedback. Thx!

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I read the introduction, looks very good to me!
One thing that I think, is after clicking on introduction on home page, it takes to toctree, and we have to move further with no information on that page. Instead of that, the introduction button on home page could take directly to intro page would be better, I think. Otherwise, the current version looks very interesting to read

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, could you take over the updates for Section 2 "Getting Started"? 

- New install option "full" for pypi
- Question: is there a possibility to let pip (or a different tool) list all depending packages behind option "full" before installation?

**Comment by steveyuwono** [comment]
Hi @detlefarend, I have checked the introduction part. They look fascinating and satisfactory to me as well as the contents. I made a minor correction after checking them through Grammarly. Just a sentence sounds weird to me, as follows:

'**In fact, with each new feature, we think about how deep we can sink it into MLPro. The deeper the place the more universal is the usability and thus the range within MLPro.**' in Section 1.2 Architecture.
Proposal: '**In fact, with each new feature, we consider how deeply we can incorporate it into MLPro. The deeper the place, the more universal the usability, and thus the range within MLPro.**'

**Comment by rizkydiprasetya** [comment]
@detlefarend done, you can check.

It is possible using johnnydep package.
https://github.com/wimglenn/johnnydep

**Comment by detlefarend** [comment]
Hi @steveyuwono, thank you for your feedback! I've changed the passage accordingly.

**Comment by detlefarend** [comment]
> @detlefarend done, you can check.
> 
> It is possible using johnnydep package. https://github.com/wimglenn/johnnydep

Good to know about this package. Question: can we use johnnydep in our pypi action after deployment to create a text file in branch main? We could then just refer to this text file from rtd. The background is that I want to avoid maintaining all these version numbers in more and more different files. I guess, we have currently at least 3 files with fixed versions.

**Comment by steveyuwono** [comment]
@detlefarend @rizkydiprasetya I just updated the format by adding points for different sections and processes.

**Comment by rizkydiprasetya** [comment]
I think with johnnydep, our package needs to be published first in PyPi then it can be read by johnnydep. Otherwise, we can read the setup.cfg and put it on a text file and refer to it on RTD.

Yes, we can have separate section.

**Comment by detlefarend** [comment]
> I think with johnnydep, our package needs to be published first in PyPi then it can be read by johnnydep. Otherwise, we can read the setup.cfg and put it on a text file and refer to it on RTD.
> 
> Yes, we can have separate section.

Yes, I also think that jd can just work after deployment to pypi. However, referring to an extract based on setup.cfg or even directly to setup.cfg is better.

**Comment by rizkydiprasetya** [comment]
I see yes. The we can do so, I think it is easier to deploy first and just save all the output from johnnydep to txt file and refer it on rtd. Would be more cleaner this way I would say. I can do this now, if agreed.

**Comment by detlefarend** [comment]
> I see yes. The we can do so, I think it is easier to deploy first and just save all the output from johnnydep to txt file and refer it on rtd. Would be more cleaner this way I would say. I can do this now, if agreed.

Yes, agreed. Thank you!

**Comment by rizkydiprasetya** [comment]
I changed the method. If we do the generation after the deployment, then we need to push it to the tagged version which something we shouldn't do. So instead of that, I created a CI which will generate the dependencies list on push or pull request.

**Comment by detlefarend** [comment]
> I changed the method. If we do the dependencies list generation after the deployment, then we need to push it to the tagged version which something we shouldn't do. So instead of that, I created a CI which will generate the dependencies list on push or pull request.

But isn't it too early, especially if we change a version number? Or do you extract the data from setup.cfg instead of using johnnydep?

BTW: you can let rtd create a table from a csv file. If you replace all "==" or "<=" by a "," then the file can be used directly.

https://tables-with-sphinx.readthedocs.io/en/latest/csv-table.html

**Comment by rizkydiprasetya** [comment]
I extract from setup.cfg.

**Comment by rizkydiprasetya** [comment]
> BTW: you can let rtd create a table from a csv file. If you replace all "==" or "<=" by a "," then the file can be used directly.
https://tables-with-sphinx.readthedocs.io/en/latest/csv-table.html

hmm interesting, then it can be automated or? should it be also in .csv or it doesn't matter?

**Comment by rizkydiprasetya** [comment]
![Screenshot 2023-01-24 at 16 40 41](https://user-images.githubusercontent.com/75730306/214338953-d9e3cbb3-6bc0-4463-99c8-c15602b8c108.png)

okay, it works. I will make some changes.

**Comment by detlefarend** [comment]
Great!! One small thing. It seems that the first row is used as table header line. Try :header-rows: 0 or maybe you can add a first row "Package, Version" to the file...

**Comment by rizkydiprasetya** [comment]
Yep, done.

**Comment by detlefarend** [comment]
Nice! Shall we remove the hint for johnnydep? It's not needed any more.

**Comment by detlefarend** [comment]
Hi guys, I reviewed both sections again. I restructured section 2 a bit and added some further hints due to compatible versions of depending packages. Hope that all of you are fine with it.

**Comment by rizkydiprasetya** [comment]
Looks great
