### ISSUE TITLE
RTD: Basic Functions

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#149]
Subsections to be documented:

- [x] **Overview** (Detlef)
    - [x] Image: Overview BF    
          ... to be completed: bf.systems, bf.ui.sciui, ...
    - [x] Introduction  
        
- [x] **Layer 0 - Elementary Functions** (Steve, Detlef)
    - [x] Logging (Detlef)
    - [x] Data Management (Steve)
    - [x] Plotting (Detlef)
    - [x] Time Measurement (Steve)
    - [x] Scientific Referencing (Steve)

- [x] **Layer 1 - Computation** (Detlef)
    - [x] Event Handling
    - [x] Multitasking
    - [x] Operations (Scenarios) 
       
- [x] **Layer 2 - Mathematics**
   - [x] Introduction and related model landscape class diagram
   - [x] Description: Dimension, Set, Space, Element, Function
   - [x] Normalizers (Laxmikant)

- [x] **Layer 3 - Application Support**
    - [x] Stream Processing (Laxmikant)
        - [x] Stream providers and streams
        - [x] Stream tasks and workflows
             - [x] Visualization
         - [x] Stream scenarios
         - [x] Pool objects: native streams, tasks
     - [x] Physics (Steve)
     - [x] State-based Systems (Laxmikant)
         - [x] MuJoCo Integration (Rizky)
         - [x] Hardware Access (Laxmikant)

- [x] **Layer 4 - Machine Learning**
    - [x] Introduction (Detlef)
    - [x] The Adaptive Model (Detlef)
    - [x] ML Scenarios (Detlef)
    - [x] Training and Tuning (Detlef)
    - [x] Adaptive Workflows (Detlef)
    - [x] Adaptive Functions (Detlef)

**Further hints**
The documentation itself shall be taken over from the related modules as far as possible and senseful.

**Comment by detlefarend** [comment]
Hi guys, I just updated/assigned the docu tasks as discussed last Friday.

@Rizky: I added a subsection for MuJoCo under Layer 3->State-based Systems.

**Comment by detlefarend** [comment]
@laxmikantbaheti I added subsections to Layer 4 ML. Subsection "Adaptive Systems" is yours.

**Comment by laxmikantbaheti** [comment]
> @laxmikantbaheti I added subsections to Layer 4 ML. Subsection "Adaptive Systems" is yours.

Ok, thank you!

**Comment by detlefarend** [comment]
Hi guys, I documented the intro for machine learning. Please take a look and give me feedback about it. Thank you!

**Comment by detlefarend** [comment]
@laxmikantbaheti I was able to spend a little time on the streams section. It reads very well and conclusively. I have currently just some annotations and proposals regarding the structure of the section:
- Title of the section: 3.5.1 Stream Processing
- images better left-aligned
- 3.5.1.3 Stream Scenario as sub-section of 3.5.1.2 Stream Processing
- Tasks in a sub-section 3.5.1.3 Task Pool

**Comment by laxmikantbaheti** [comment]
> @laxmikantbaheti I was able to spend a little time on the streams section. It reads very well and conclusively. I have currently just some annotations and proposals regarding the structure of the section:
> 
> * Title of the section: 3.5.1 Stream Processing
> * images better left-aligned
> * 3.5.1.3 Stream Scenario as sub-section of 3.5.1.2 Stream Processing
> * Native sample streams in sub-sectionn 3.5.1.3 Pool of Benchmark Streams
> * Tasks in a sub-section 3.5.1.4 Pool of Tasks
> 
> Let's discuss it further in our next QA session...

Hi @detlefarend , thank you for your review and feedback. I will do this. I still need to add info about the new native stream objects. I will update the documentation accordingly and let you know.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I removed subsection BF-ML-Systems from the issue. Let's describe this in the next release...

**Comment by detlefarend** [comment]
@steveyuwono @laxmikantbaheti @rizkydiprasetya I have completed subsection BF-ML. Could someone review it and give me some feedback? Thanks!

**Comment by steveyuwono** [comment]
> @steveyuwono @laxmikantbaheti @rizkydiprasetya I have completed subsection BF-ML. Could someone review it and give me some feedback? Thanks!

Perfect, thank you. I will take a look at it later today.

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, I removed subsection BF-ML-Systems from the issue. Let's describe this in the next release...

Thanks. I agree.

**Comment by steveyuwono** [comment]
> @steveyuwono @laxmikantbaheti @rizkydiprasetya I have completed subsection BF-ML. Could someone review it and give me some feedback? Thanks!

Looks good to me!

**Comment by laxmikantbaheti** [comment]
> @steveyuwono @laxmikantbaheti @rizkydiprasetya I have completed subsection BF-ML. Could someone review it and give me some feedback? Thanks!

Hi @detlefarend , I read it, and it looks very good to me, all the sections are concise and informative.

For now I just spotted one typo:
- in 3.6.1  "to (paralle**lly**/asynchronously) **execute**" in Performant execution

And also, maybe the use of term "so-called" can be interpreted sometimes a bit negative...

**Comment by detlefarend** [comment]
> > @steveyuwono @laxmikantbaheti @rizkydiprasetya I have completed subsection BF-ML. Could someone review it and give me some feedback? Thanks!
> 
> Hi @detlefarend , I read it, and it looks very good to me, all the sections are concise and informative.
> 
> For now I just spotted one typo:
> 
>     * in 3.6.1  "to (paralle**lly**/asynchronously) **execute**" in Performant execution
> 
> 
> And also, maybe the use of term "so-called" can be interpreted sometimes a bit negative...

Hi @laxmikantbaheti, thanks for your feedback. I fixed the type but I didn't find "so-called". Did you already remove it?
