### ISSUE TITLE
Env MultiCartPole: Freeze single envs when done

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#160]
The MultiCartPole env returns done=True, when all gym envs inside have done. The problem is that for instance the first env that has done produces a warning and behaves undefined until the next overall reset.

The best would be, that envs that have done get freezed. Means: no further steps and no further rewards until next overall reset...

Implementing this is also a good validation for selective rewarding/adapation in the RLScenario cycle...

Can be tested/validated in Howto 04 (RL), that currently throws Gym warnings about unexpected steps (after env has done)...

Coach: @detlefarend

**Comment by laxmikantbaheti** [comment]
![pycharm64_2022-04-06_16-21-17](https://user-images.githubusercontent.com/100450659/161997415-501dc7ec-8703-4dfc-b3e9-538e51d0ae30.gif)

the freezing visualisation can be seen in this gif

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, is this activity ready for review? If yes, please create a new pull request and assign this issue. Thank you!
