### ISSUE TITLE
RTD: Commented EnvModel Class Diagram

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#187]

**Comment by budiatmadjajaWill** [comment]
@detlefarend Please check the latest diagram when you have the time. Thank you.

**Comment by detlefarend** [comment]
> @detlefarend Please check the latest diagram when you have the time. Thank you.

Hi @budiatmadjajaWill, here's what I found:
- custom method _simulate_reaction() is missing (even if it is rather a theoretic scenario)
- please place the 4 custom methods of block 3 directly below the last of their public counterpart methods
- method switch_logging(): there is no default value for parameter p_logging

**Comment by budiatmadjajaWill** [comment]
Since p_afct_strans is mandatory, I still didn't add that to block 3. Instead I added a small explanation about this on the yellow notes.

**Comment by detlefarend** [comment]
> Since p_afct_strans is mandatory, I still didn't add that to block 3. Instead I added a small explanation about this on the yellow notes. 

Of course you are right.
