### ISSUE TITLE
RL-TRAIN: Universal Scoring Equation

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#212]
The first approach 

`score = max( self._eval_num_done - self._eval_num_limit - self._eval_num_broken, 0) * mean(self._eval_max_reward) * self._eval_factor / self._eval_num_cycles
`

is a little bit complicated and carries the risk of premature stagnation at the beginning of the training because of term 1. 

After a detailed team discussion we agreed to  the following simplifed approach:

`score = sum ( mean_reward_epi ) `

where `mean_reward_epi` is the mean reward of all cycles of an evaluation episode. It is set to 0 if the env goal was not reached.

See method RLTraining._close_evaluation()

**Comment by detlefarend** [comment]
Question: can we be sure that a reward is ALWAYS >=0 ?

**Comment by budiatmadjajaWill** [comment]
I don't think so..

**Comment by detlefarend** [comment]
Then the question is how we reward an evaluation where no episode terminated in a done state.

**Comment by budiatmadjajaWill** [comment]
Didn't we agree to just use the mean?

**Comment by detlefarend** [comment]
In my understanding we agreed, that we compute the mean for every episode. And just in case that an episode terminated in a done state this mean value is summed up to the overall reward of the entire evaluation.

**Comment by budiatmadjajaWill** [comment]
Yes, then what's the problem?

**Comment by detlefarend** [comment]
What is the overall reward of the evaluation if no episode terminated in a done state?

**Comment by budiatmadjajaWill** [comment]
Maybe it should be 0 then

**Comment by rizkydiprasetya** [comment]
It doesn't matter. Either with done or not, the reward itself represents everything. "Done" just means something extra to the reward. On the reward function itself, if it reaches the goal, there will be an extra reward. So it should be doesn't matter.

**Comment by detlefarend** [comment]
That means, we just compute the mean reward over all eval cycles indepently of episodes terminated in done state or not?

**Comment by rizkydiprasetya** [comment]
So, basically mean([sum(reward_cycle_epi_1), sum(reward_cycle_epi_2), sum(reward_cycle_epi_3), .........])

**Comment by rizkydiprasetya** [comment]
Currently, I am thinking something in more general, because if we are based only on reward, then if the user changes the reward function, the score will be different, and will not be comparable with the previous reward function.

**Comment by rizkydiprasetya** [comment]
Why not? because an environment could have a discrete reward. For example, cart pole has discrete reward. If you take mean of all cycles then the score will be always 1.

**Comment by rizkydiprasetya** [comment]
> Currently, I am thinking something in more general, because if we are based only on reward, then if the user changes the reward function, the score will be different, and will not be comparable with the previous reward function.

For this, I think we can skip. We will restrict only for the same reward function. Otherwise will be complicated. So, forget this.

**Comment by detlefarend** [comment]
> Why not? because an environment could have a discrete reward. For example, cart pole has discrete reward. If you take mean of all cycles then the score will be always 1.

Öhm, no. We have an epi with 5 cycles and env rewards: 0, 1, 1, 0, 1 then the score is 3/5 = 0.6

**Comment by rizkydiprasetya** [comment]
No, Cartpole cannot have 0 reward, only 1. Please check. https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

**Comment by rizkydiprasetya** [comment]
And also it doesn't make sense at all, if we take only mean of all cycles. You need reward from the whole episode, not per cycle.

**Comment by detlefarend** [comment]
> No, Cartpole cannot have 0 reward, only 1. Please check. https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

Ok wait: I am in a state s1 and carry out an action a that brings me to a subsequent state s2. I reward by definition s1, s2 -> r. And in case of cartpole it's always 1???

**Comment by rizkydiprasetya** [comment]
yes

**Comment by rizkydiprasetya** [comment]
> And also it doesn't make sense at all, if we take only mean of all cycles. You need reward from the whole episode, not per cycle. So, it should be mean of reward episode.

For example, Atari game, you don't take score from every cycle, or every action that you take, but the score is from the end of the game after game over.

**Comment by detlefarend** [comment]
That makes no sense and they described it here in a different way: https://gym.openai.com/envs/CartPole-v0/

**Comment by rizkydiprasetya** [comment]
> That makes no sense and they described it here in a different way: https://gym.openai.com/envs/CartPole-v0/

Yeah anyway please read this logic. 



> > And also it doesn't make sense at all, if we take only mean of all cycles. You need reward from the whole episode, not per cycle. So, it should be mean of reward episode.
> 
> For example, Atari game, you don't take score from every cycle, or every action that you take, but the score is from the end of the game after game over.

**Comment by rizkydiprasetya** [comment]
> That makes no sense and they described it here in a different way: https://gym.openai.com/envs/CartPole-v0/

This is old, should be CartPole-v1

**Comment by detlefarend** [comment]
The description of v0 is right. The reward is 1 only if the pole is in tolerance. Here's the original problem definition of Sutton, Barto 1983 (doi 10.1109/tsmc.1983.6313077):

![grafik](https://user-images.githubusercontent.com/79243976/146586425-85db4544-c535-4a40-a596-bc7d86a1b88e.png)

**Comment by detlefarend** [comment]
Ok, my mistake! The reward is 1 if the pole is in tolerance. Otherwise the episode terminates.

**Comment by rizkydiprasetya** [comment]
Again, another analogy, if you play an arcade game, do you take the high score from every action that you take, or at the end of the game?

**Comment by detlefarend** [comment]
Ok, back to sub-scoring every evaluation episode.

Currently I think, the evaluation strategy depends on the env.

Cartpole:
Try to keep the pole vertical. The longer the better. Means: more cycles are better.

General control loop: 
Try to eliminate to control error as fast as possible. Means: more cycles are worse.

**Comment by rizkydiprasetya** [comment]
So, the scoring, if you take only the reward, then you don't have to worry anymore about which env. **Reward itself already represents everything**. 

So, I will stick with mean of reward episode.
