### ISSUE TITLE
RL-ENV UR5 Joint Control in a Docker Container

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#227]
...

**Comment by detlefarend** [comment]
> We want to do this after release 0.8.0, right ?

Yes, it's future work. Maybe for release 1.0.0.

**Comment by rizkydiprasetya** [comment]
We should have our own docker hub account. So later on the user can pull the image from the hub. We can publish 3 images I think. 
1. MLPro (This, if the user wants to run the code completely from a container)
2. UR5 Env (This, if the user wants to run the UR5 environment on a container, but the training code from the host)
3. MultiGeo Env (This, if the user wants to run the MultiGeo environment on a container, but the training code from the host)

**Comment by budiatmadjajaWill** [comment]
Note from last meeting:

- Docker is postponed from V1 release.
- For future work, the docker should have an option to work with some kind of API so that the script is running both in the container and in the host. 
- Xserver should also be tested for GUI http://wiki.ros.org/docker/Tutorials/GUI

**Comment by rizkydiprasetya** [comment]
Planning:

- [ ] Dockerfile; MLPro installation and UR5 ROS Workspace
- [ ] Communication between Container and Host (eg, Training Code in Windows, Simulation in Container), this is for separate training and simulation.
- [ ] Standalone container, where the training and the simulation are in the container. One of possibility is to use the container as a development container, where the user will develop everything inside this container.

**Comment by rizkydiprasetya** [comment]
Closing this, move to another repo.
