### ISSUE TITLE
README.md: Optimization

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#236]
This file is the visiting card of our project and framework. It is visible on GitHub and PyPI and should be as clear, informative (but not complicated) compact, appetizing and fancy as possible...

Any ideas for improving and/or beautifying are welcome!

**Comment by rizkydiprasetya** [comment]
The installation instruction is not there?

**Comment by detlefarend** [comment]
> The installation instruction is not there?

I removed it to avoid redundancy. On the PyPI the install command is visible on top by default. On GitHub it's not but we provide a link to the docu. I think we should describe everything related to the installation and quick start once on RTD and then just refer to it. A related issue is #130...

**Comment by rizkydiprasetya** [comment]
The we can separate, readme for GitHub and readme for PyPi

**Comment by rizkydiprasetya** [comment]
PyPi should contain:
- Small Introduction (Overview)
- Link in to our repo, documentation
- Snippet of an example

GitHub should contain:
- Overview
- Installation
- More details about the project
- About the team
- How to contribute
- And give more details

So, PyPi should contain less compact information, no need too detail, because it is just like a portal to our GitHub Repo. Less people actually read description on PyPi. They jump directly on any Open Source repo.

**Comment by detlefarend** [comment]
The leading documentation platform and entry point for interested people is RTD. Installation details, examples, ... are documented there. The readme on GitHub/PyPI is just a first orientation and appetizer for people which found us there. But if someone really wants to try MLPro he/she needs to visit us on RTD anyway.

And installing MLPro is not just one line. The installation instructions with all dependencies and options (#130) will grow and should be documented once. Examples are exactly the same story.  Let's try to avoid redundancies and document the things once - as far as possible.

But we could add a link to the install section in RTD to the README.md.

**Comment by rizkydiprasetya** [comment]
It is just three lines according to #130, what is the problem? The rest is on the RTD.

**Comment by rizkydiprasetya** [comment]
I am not talking about documentation platform. its "README".

**Comment by rizkydiprasetya** [comment]
Do you understand the difference between README and Documentations?

**Comment by rizkydiprasetya** [comment]
README, should contain informations that allow the user to start a simple program. To test it, and feel it. If they are interested in the first sight and want to try it more deeper than that, then they should go to the documentations.

**Comment by detlefarend** [comment]
I just took a look at two other frameworks. They have very extensive readme files with installation routine and examples as well. To be honest I have some doubts regarding the redundancies but finally - why not. Can we separate the example code in an extra file and auto-test it on merge time?

**Comment by rizkydiprasetya** [comment]
Yeah sure why not. We can have something simpler.
