### ISSUE TITLE
RL: Training - Improvement of stagnation detection

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#265]
The current algorithm for stagnation detection compares the last n scopes directly. Stagnation is assumed, if there was no increase of the scope for n times.
This criterion behaves foreseeable unsatisfactory in case of alternating scopes in the end phase of the training.
The algorithm can be improved by tracking

**1. The moving average of the scope**
Advantage: easy and performant computation
Disadvantage: the first coimparable value is available after n evaluations at the earliest. Then it takes further n-1 evals to be able to make a decision. Stagnation can be detected at the earliest after 2n - 1 evaluations. 

**2. The Slope of the regression line of the last n scopes**
Advantage: a decision can be made after n evaluations. Numpy supports linear regression.
Disadvantage: runtime complexity is higher because of optimization.
See also: https://sodocumentation.net/numpy/topic/8808/simple-linear-regression

**3. Further approaches (...)**

**Comment by detlefarend** [comment]
Hi colleagues, any further ideas?

**Comment by budiatmadjajaWill** [comment]
Have we implemented something like a patience buffer ? So that it doesn't get cut off right away.

**Comment by detlefarend** [comment]
> Have we implemented something like a patience buffer ? So that it doesn't get cut off right away. 

I described the current algo in the issue text.

**Comment by budiatmadjajaWill** [comment]
Maybe we can try to implement trend searching algorithm like Parabolic SAR.

**Comment by detlefarend** [comment]
Hi colleagues, I created a new template class TrendAnalyser to bf.math. Furthermore there is a related new pool: ./bf/pool/trendanalyzer to place algorithms. Please take a look in branch model_improvements9 and let me know if there is something missing. Thx!

**Comment by detlefarend** [comment]
I added moving average score computation. Its horizon can be adjusted with parameter p_score_ma_horizon (default=5). It's the base for stagnation detection now and it is also added as column to result file evaluation.csv.
