### ISSUE TITLE
RTD/Howto 21 - (RL) Train and Load Single Agent: run scenario instead of further training

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#326]
The howto shall demonstrate a training and the use of the trained agent. For this, the second training should be replaced by simply running the scenario MyNDScenario. Furthermore, the comments and their numbering should be cleaned up.

**Related issue:** #324 (simplifies the reuse and makes an own implementation of a scenario just for loading the module unneccessary)

**Hint:** please use to current rtd branch to avoid conflicts with further documentation activities!!

**Comment by rizkydiprasetya** [comment]
@detlefarend the second training is using the MyNDScenario. So, what is missing?

**Comment by rizkydiprasetya** [comment]
Done

**Comment by detlefarend** [comment]
Aww, obviously I described the issue misunderstandingly:-( It was not intended to remove all comments. These are still senseful for all people who are new to MLPro.

**Comment by rizkydiprasetya** [comment]
Done
