### ISSUE TITLE
BF-Systems : MuJoCo Integration

### ISSUE THREAD

**Issue by rizkydiprasetya** [fhswf/MLPro#344]
MuJoCo is now free and open source. It is maintained by DeepMind. MuJoCo is Multi-Joint Dynamics with Contacts. It provides fast and accurate simulation for robotics, biomechanics, graphics and animation, machine learning.

The integration allows us to use MuJoCo simulation to be used as the environment in the reinforcement learning. The advantage of MuJoCo is that it can be used on all platforms (Linux, MacOS, Windows)

https://mujoco.org/

- [ ] New Howto RL 26

**Related issues**
#549

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, I took a look. The integration seems to be ok so far. Here's my feedback:

State space:
In howto bf-systems-002 it is set manually. We already talked about auto-extraction from the XML file. Is this already implemented or are there reasons not to do this? If we can't extract the space automatically, all mujoco systems need to be wrapped. Means: system classes for all mujoco samples.

Howtos:
- Should demonstrate/validate auto-extraction of state space (if possible)

RTD, general:
Please check grammar with grammarly.

RTD, bf.systems.mujoco:
-The possibilities of editing mujoco files should be pointed out. E.g. the unity project (https://mujoco.readthedocs.io/en/stable/unity.html) and further ones.
- cross referencing of howtos (please just the title (not file name) of the howto. please compare with other sections)
- cross referencing to wrapper 
- cross referencing to further sample systems in the internet

**Comment by rizkydiprasetya** [comment]
- State Space:
The reason is state space can be anything not limited only to a state from MuJoCo itself. State can be also a product after some calculation from MuJoCo. For example, I want to put distance between current position and goal position as a state. Current position and goal position can be retrieved from MuJoCo, but the distance needs to be calculated manually. So it is more flexible.

- Auto extraction is possible if we only focus on state from MuJoCo. Nothing else.

- What do you mean by this "cross referencing to further sample systems in the internet"? One of them is mentioned above in the description where you can find sample of xml file.

**Comment by rizkydiprasetya** [comment]
I dont understand also with the following:
"cross referencing of howtos (please just the title (not file name) of the howto. please compare with other sections)"
which one?

**Comment by rizkydiprasetya** [comment]
Grammar check done.

**Comment by detlefarend** [comment]
I forgot to mention that it's the same for the action space...

Action space:
It seems to be deterministic. The XML file has a node <actuator>.

State space:
Do you mean space generation based on a sample/initial state (method get_flattended_state())? If yes: that's better than nothing. 

Cross references:
Please use the title of the howto only:

![image](https://user-images.githubusercontent.com/79243976/218444382-a036cf27-8d86-4617-b9c0-190f321608e5.png)

**Comment by rizkydiprasetya** [comment]
Then I will just leave it auto generated. I will change it.

**Comment by rizkydiprasetya** [comment]
Done, you can check again.

**Comment by detlefarend** [comment]
I have spent more time with the wrapper and got some ideas for further improvements. Let's discuss this in our next meeting. Here are my proposals in advance:

**RTD**
- Hint of visualizing and editing MuJoCo files with external tools (project unity, the view you showed me, ...)
- Sub-section for the pool of sample systems

**Class System**
- MuJoCo: get system name and latency from file/model
- All cases: logging of state space, action space, latency

**Howtos**
To be able to assess, validate, and improve the wrapper better, I propose a howto for each sample system with these steps
- instantiate the wrapper (own system child class should not be necessary)
- wait until the user presses ENTER (to see the logs of spaces, latency, ...)
- run the demo cycles
