### ISSUE TITLE
Howto RL-008 (Wrapped MLPro env): Number of resets

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#348]
In Howto RL-008 (new numbering!) the log shows weird behavior. Please check whether this is a bug in the Gym wrapper. 

![grafik](https://user-images.githubusercontent.com/79243976/170943348-52dc94ec-9317-493f-b996-15cff472d656.png)

**Comment by rizkydiprasetya** [comment]
@detlefarend which gym version are you using?

**Comment by steveyuwono** [comment]
The 'instantiated' is printed twice due to:
https://github.com/fhswf/MLPro/blob/74f22f786bdb581c1e41c030ffe1c1630d5eab68/src/mlpro/rl/models_env.py#L925-L933

**Comment by steveyuwono** [comment]
The reset is called three times because of env_checker.py
![image](https://user-images.githubusercontent.com/88610818/170949351-eb7940c0-e8f1-4e37-9ef2-2bc748c02e1b.png)

**Comment by rizkydiprasetya** [comment]
> The 'instantiated' is printed twice due to:
> 
> https://github.com/fhswf/MLPro/blob/74f22f786bdb581c1e41c030ffe1c1630d5eab68/src/mlpro/rl/models_env.py#L925-L933

@detlefarend this is true. It also happens on other Howto.
