### ISSUE TITLE
Paper "MLPro - An integrative middleware-framework for standardized machine learning tasks in Python"

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#352]
Spinoff paper:

- [x] Journal: [Elsevier - Software Impacts](https://www.journals.elsevier.com/software-impacts) 
- [x] Title: "MLPro - An integrative middleware-framework for standardized machine learning tasks in Python"
- [x] Highlights (Detlef)
- [x] Abstract (Steve/Detlef)
- [x] Part 1: Introduction (Steve/Detlef)
- [x] Part 2: Functionalities and key features
    - [x] 2.1: Core concepts (Detlef)
    - [x] 2.2: MLPro-RL (Detlef)
    - [x] 2.3: MLPro-GT (Steve)
    - [x] 2.4: Wrappers
- [x] Part 3: Impact (Detlef)
- [x] Part 4: Future improvements (Detlef)
- [x] Declaration of competing interest
- [x] Acknowledgement
- [x] Funding
- [x] References
   - [x] Entry for MLPro Github repo with DOI on Zenodo (Detlef) 
   - [x] Entries for Code Ocean capsules (Detlef)
- [x] Videos (Rizky/Steve)
  - [x] #359 
  - [x] #362  
- [x] Internal Review 
- [x] Submission Elsevier (Detlef)
  - [x] Initial submission
  - [x] Revision
  - [x] Final submission 

**Comparable articles:**
- [Spark NLP: Natural Language Understanding at Scale](https://reader.elsevier.com/reader/sd/pii/S2665963821000063?token=A16592A476DB78F8D4E644067343096DE22E407DDF5AA0898F8AE8FA49F62C8E635C4B0063E25DC837ABE4E8515B0D0B&originRegion=eu-west-1&originCreation=20220610131643)
- [Cardinal, a metric-based Active learning framework](https://reader.elsevier.com/reader/sd/pii/S2665963822000173?token=4C625EAB513FE18A1E258C9E98E879ABB5C61C2893FAF5A0708B32008BBD84EEB2D72F7E2F9B6DF4677B7F430AFB51F7&originRegion=eu-west-1&originCreation=20220610133533)
- [DRAS-CQSim: A reinforcement learning based framework for HPC cluster scheduling](https://reader.elsevier.com/reader/sd/pii/S2665963821000257?token=90C34F72C25162245321527F96F7A068E7C14AA85B134DDA5D14C3783EE6125DE0BE7F475CFF72EB0C709A982A99A3E0&originRegion=eu-west-1&originCreation=20220610134136)

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya @steveyuwono, I thought about the title and propose the origin one (= RG project title) for this paper: **MLPro - A synoptic framework for standardized machine learning tasks in Python.** 

I think that fits because Journal SI has a more general and less detailed view to software projects, while the related MLWA articles provide a deep insight to details of a framework. In that sense I would add only one article for the entire project in SI. Details of future extensions can then be described in MLWA.

Please let me know if you have doubts or a better idea.

**Comment by steveyuwono** [comment]
Okay, I have no better idea at the moment. We can use the title.

**Comment by detlefarend** [comment]
Hey guys, what do you think of this title:

**MLPro - An integrative middleware-framework for standardized machine learning applications in Python**

Worse or better?
