### ISSUE TITLE
Wrapper for River data streams

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#354]

**Comment by detlefarend** [comment]
Hi Laxmikant, I took a look at the related howto and found out that class WrStreamRiver obviously stores instances as dictionaries. That's a problem. Instead, the values should be stored as single values or numpy array. Maybe something to review in our next meeting....

![grafik](https://user-images.githubusercontent.com/79243976/174478540-d7df143e-853d-4aaf-8144-267ecb20c596.png)

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I updated the instances to now be a Numpy Array.
