### ISSUE TITLE
Video 1: MLPro - Core Concepts / Introduction

### ISSUE THREAD

**Issue by rizkydiprasetya** [fhswf/MLPro#359]
- [x] What is MLPro?
- [x] What is it for?
- [x] Github hosted
- [x] RTD

Fundamentals Code Object
- [x] Model
- [x] Scenario
- [x] Training/Tuning

**Comment by steveyuwono** [comment]
[Script - draft_01.docx](https://github.com/fhswf/MLPro/files/8991883/Script.-.draft_01.docx)

**Comment by steveyuwono** [comment]
[Script - draft_01.docx](https://github.com/fhswf/MLPro/files/8991913/Script.-.draft_01.docx)
