### ISSUE TITLE
Wrapper SB3: Improved C_TYPE/C_NAME for logging

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#380]
Currently class WrPolicySB32MLPro has 

C_TYPE = 'SB3 Policy'
C_NAME = '????'

That leads to log entries like this:

![grafik](https://user-images.githubusercontent.com/79243976/185881903-def4f10e-cd16-451b-bb63-5421893361e5.png)

The following changes are proposed (similar to gym wrapper):
C_TYPE = 'Wrapper SB3 -> MLPro'
C_NAME = 'Policy' + [SB3 Policy Name]

**Comment by rizkydiprasetya** [comment]
done
