### ISSUE TITLE
OA-Task Boundary Detector

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#384]
A new pool class 'BoundaryDetector' shall be implemented. The class determines whether a component of an incoming input is outside the boundaries of the related dimension. In that case, the boundaries of the related dimension shall be extended.

- [x] **New module ./oa/pool/tasks/boundarydetectors.py**
- [x] **New class BoundaryDetector (inherited from OATask)**
- [x] **Implementation of custom methods**
   - [x] **Method _adapt( p_inst_new:list )**
     Compares values in p_inst_new with boundaries of related set. If an update of the boundaries has been done, the method shall return True.  
   - [x] **Method _run( p_inst_new:list, p_inst_del:list )**
   Calls method adapt (not _adapt!!) if p_inst_new is not empty and p_inst_del is empty.
   - [x] **Method _adapt_on_event( p_event_id, p_event_obj:Event )**
   Event handler method to be registered on event C_EVENT_DATA_REMOVED of class oa.Window. Uses method get_boundaries() of raising object to determine the new boundaries. Object p_event_obj contains a reference to the related Set (to be specified in class Window).
   - [x] **Plot functionality**
      - [x] As separate plot
      - [x] View nD
      - [x] View 2D
      - [x] View 3D

**Further hints:**
See class diagram for further details.
See class bf.ml.MLTask for further details of event-based adaptation.

**Dependencies:**
#388 #245 #391 #402 #450    

**Branch:**
online_adaptivity6

**Comment by detlefarend** [comment]
Approved for implementation

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I reworked the specification. My estimation is, that it's not that easy to understand but easy to implement. If you have any questions or better ideas, please let me know...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, please remove event C_EVENT_BOUNDARY_CHANGED. It is enough to let method _adapt() return True on adapation. Then, method adapt() will automatically raise event C_EVENT_ADAPTED.

**Comment by detlefarend** [comment]
I also extended the spec due to extra plot functionality.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti could you please refactor the BD after our changes of the day (set -> list)?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, the BD raises an exception during first adaptation. See howto 001.

**Comment by laxmikantbaheti** [comment]
hi @detlefarend , the bugs are fixed

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I examined the behavior of the stream/oa tasks a bit more. I howto 003 the bd just visualizes boundaries [-10,10] and I guess it takes the values from the boundaries of the related dimensions. But that's not the purpose here. The bd shall automatically find (and set) the real boundaries. I raised the handicap a bit and removed the boundaries of native stream "MLProRND10D". Now the bd raises an exception. Could you please check it? Thx!

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the bd checks the values from the new instances itself. There was a bug, an i instead of 1. I fixed it. Now it works.

About the color and legend management, I wanted to suggest that we add legends to the main workflow plot and assign specific colors to features in the framework, which later can be accessed in each plot.

**Comment by laxmikantbaheti** [comment]
> There's a problem still, the normalized values are not within -1 and 1. I'll check.

I've fixed it, now you can see the boundaries changing after some runs

**Comment by detlefarend** [comment]
Here I found a small bug: 

![Image](https://user-images.githubusercontent.com/79243976/208752938-da44ea28-b281-4b53-b2bf-ba6de8d6e56c.png)

Please initialize with [ value * scaler[i], value * scaler[i] ] instead [0,0].

**Comment by laxmikantbaheti** [comment]
Ah, yes! Sure! It was just adding a step.
