### ISSUE TITLE
BF-ML: Classes HyperParam, HyperparamTuple - Review callback mechanism

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#389]
Shall be reviewed and eventually replaced by event handling...

Dependencies:
#388

**Comment by detlefarend** [comment]
Hi @steveyuwono, I replaced the callback-mechanism of the classes by event handling. Do you use this mechanism anywhere?

**Comment by steveyuwono** [comment]
Hi @detlefarend , I just checked the codes and I do not use the callback-mechanism anywhere.
