### ISSUE TITLE
Release-Checklist

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#399]
A checklist for all necessary steps before, during and after a new release shall be established. Similar to a PR-Checklist it shall come up during a release/tagging.

- [x] Checklist with tasks to be ticked off
- [ ] Integration into GitHub release/tagging process

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, could you please check the possibilities in GitHub for this? I guess/hope that we could do something similar to what you have set up for pull requests (this template checklist thing...).

**Comment by rizkydiprasetya** [comment]
@detlefarend We can create issue template specifically for release checklist.

**Comment by rizkydiprasetya** [comment]
I already put it here: https://github.com/fhswf/MLPro/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md

So when you create new issue, you can choose the checklist issue template.
