### ISSUE TITLE
RTD: Reference to Release Notes in GitHub

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#400]
GitHub offers release notes. It optionally creates a draft based on the names of the related pull requests. These notes should be used instead of a separate text file in RTD...

Tasks are:
- [x] Standard layout
- [x] Update of all notes of the past releases
- [x] RTD: reference to GitHub release notes instead of own text file

**Comment by rizkydiprasetya** [comment]
Make sure we use clear PR name. Because it is based on the name of the PR
