### ISSUE TITLE
GitHub, Anaconda and PyPI: Completion and unification of public information

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#405]
The descriptions of MLPro in GitHub (Readme.md), Anaconda and PyPI shall be completed and unified. In the best case the (textual) content can be written once and included in both control files. 

**Checklist:**

- [x] Logo
- [x] Title
- [x] Description
- [x] Contributors (link to GitHub contributors)
- [x] Related links to GitHub, RTD

**Comment by rizkydiprasetya** [comment]
@detlefarend I dont understand this unification. Can you explain more?

**Comment by detlefarend** [comment]
Hi Rizky, these three locations represent MLPro in the public. They are also a kind of marketing platforms. The information about MLPro should be identical and complete and appetizing there. The issue is not urgent and more a reminder for us.
