### ISSUE TITLE
Bug: RTD pdf generation does not work

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#412]
**1 Describe the bug**
RTD offers the possibility to generate a pdf of the entire documentation. This option is enabled but the last pdf was generated for 0.5.0. Furthermore, this documentation doesn't contain the main section level.

**2 To Reproduce**
1. Go to [MLPro docu site](https://mlpro.readthedocs.io)
2. At the bottom of the menu: open 'latest'
![grafik](https://user-images.githubusercontent.com/79243976/190337932-5faa64d5-4e23-45ea-bdd5-0db0dc73638b.png)
3. Click 'Downloads'
![grafik](https://user-images.githubusercontent.com/79243976/190337450-4f4fd921-4d2f-417d-b731-32f68605d7d4.png)
4. Available pdfs
![grafik](https://user-images.githubusercontent.com/79243976/190338332-d1d66a76-f1ae-44ff-b4d9-14c767059aa7.png)

**3 Further hints**
Maybe the problems can be solved by an additional config file in the extended settings (at the bottom)...
![grafik](https://user-images.githubusercontent.com/79243976/190339448-7412f417-f545-4030-a524-fb5207575492.png)

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, would be cool if you could take a look. Not urgent!

**Comment by rizkydiprasetya** [comment]
@detlefarend Its not a bug. I didnt set it up to do that. I will turn that on. So, do we need the other format, or just pdf?

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, I see. PDF should be enough. Thank you for turning it on!

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya there is still a problem with the toc of the pdf. And the pdf points out release 1.0.0 instead of 0.9.2. Do we have a chance to solve this?

**Comment by rizkydiprasetya** [comment]
Please create another issue with all the pdf issue list. This issue is only about generating the pdf.
