### ISSUE TITLE
BF-Streams: StreamTask Window

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#452]
New pool classes for (sliding) windows shall be implemented. Root class Window shall specify all general properties of a window (data buffer)

- [x] **New module ./bf/streams/tasks/windows.py**
   Please add an import statement to init.py.

- [x] **New class Window (inherited from StreamTask)**
    Basic implementation of a sliding window with static buffer size. Incoming instances are stored in a dictionary that is used as a ring buffer (attributes _buffer : dict and _buffer_pos : int). 
   - [x] **Method _run()**
      The next instance is stored at position _buffer_pos. After that, _buffer_pos is updated by: _buffer_pos = (_buffer_pos + 1) modulo buffersize.
       - If the buffer is filled, event C_EVENT_BUFFER_FULL shall be raised.
       - If obsolete data are removed from the buffer, event C_EVENT_DATA_REMOVED shall be raised.
    - [x] **Method get_buffered_data**
      Returns _buffer, _buffer_pos
    - [x] **Method get_boundaries()**
      Determines the boundaries of all stored instances.
     - [x] **Method get_mean()**
     Determines the mean values of all stored instances
     - [x] **Method get_std_deviation**
     Determines the standard deviation of all stored instances in relation to a mean value.
     - [x] **Visualization**
         - [x] 2D
         - [x] 3D
         - [x] nD

**Further hints:**
See class diagram for further details.

**Dependencies:**
#484 

**Branch:**
online_adaptivity7

**Comment by laxmikantbaheti** [comment]
Hello @detlefarend , if you are not currently working on this branch, shall I merge main into it? The event handler causes error otherwise.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, fine for me!

**Comment by laxmikantbaheti** [comment]
Hello @detlefarend , 
I have a doubt reagarding the obsolete data
the obsolete data in this case should be added to the p_inst_del parameter, which is then passed to further tasks in the workflow, right?

**Comment by detlefarend** [comment]
Exactly!

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I changed the context of this development as discussed in slack. You can use the same branch.

**Comment by laxmikantbaheti** [comment]
hi @detlefarend,
the WindowR is implemented completely with numpy elements, however, by this, is it suggested that the mean, variance, std, and boundaries in base window class shall be calculated by pure logic (lists, and for loops, etc.). Or shall we still use numpy methods to calculate boundaries and other statistics, since our elements themselves are already numpy arrays?
I think going wiht numpy is more efficient in both implementations. In that case only the buffer is a dictionary object in the base class.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, if the instances are stored as references in a dictionary then numpy can't be applied directly. I fear, we need to loop at the dict and also loop at all (numeric!) dims of the instances.

**Comment by detlefarend** [comment]
@laxmikantbaheti Quick recap of our today's discussion: we decided to remove class WindowR and to add optional high performance implementations of the statistic functions to class Window. A new parameter p_enable_statistics is introduced to turn on/off extra buffering of the real-valued feature data in a separate numpy array...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, fyi: the visualization will take more time but the processing itself should work now. You could set up a howto based on howto_bf_streams_101_stream_workflow_scenario1.py to validate the Window task.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti a thought about the need for duplicating data during stream processing. Originally I had the plan to provide an option on level StreamTask but now I have doubts about this. The only reason for duplicating incoming data is to prevent them for direct modification by stream tasks. And the only affected task that came into my mind is Window. It needs to buffer duplicates of incoming data because the original ones could be modified by subsequent tasks. If the buffers runs full the origin (and not the modified) data shall be induced to the subsequent tasks again - this time as data to be removed. Long story short: the best idea I have is letting the Window class store duplicates. To this regard, class Instance has a method copy(). And this is neccessary only if the subsequent tasks really modify the data. So, it should be an optional parameter. What do you thing?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , yes I wanted to ask you about the p_duplicate parameter.
I think this parameter could help in normalizers. Where we just want normalized data for a particular application, like rewarding, and we also need the original data to feed back to the simulator.

**Comment by laxmikantbaheti** [comment]
Ohh, the new method is on instance, and it can be used by any task.
Okay, yeah that will work!

**Comment by detlefarend** [comment]
I have to rethink that. I'll come back with a proposal...

**Comment by laxmikantbaheti** [comment]
Further Improvements:
- [ ] Review for memory and speed optimization
- [ ] color palette for windows in plotting

Just a note for me

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I found a gap in class Window. Parameter p_delay doesn't delay the data forwarding. I extended related howto_bf_streams_110_stream_task_window.py accordingly so that you can see the data behind the window...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, a further thing to think about is the visualization. Currently there is a box per feature but the buffered instances don't depend on the number of features. I think it's enough to show one box - and if possible - in the background of the plots and with a pale color or semi-transparent. Alternatively we could hide the non-buffered instances by a semi-transparent box in the foreground. Maybe a parameter to switch the method. Finally we want to highlight the buffered instances... Any further ideas?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , as long as we don't want to mention the boundaries of the feature in the window, showing one box will be enough. Since in 2D and nD a window is just the boundaries of the features within the window.

I agree about the colors.

**Comment by detlefarend** [comment]
Maybe we can discuss this in our next meeting.

Did you also see my comment about parameter p_delay?

**Comment by laxmikantbaheti** [comment]
> Maybe we can discuss this in our next meeting.
> 
> Did you also see my comment about parameter p_delay? 

Hi, yes, I made some changes in windows. But, there are some problems I'm facing mt level.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I just took a look at the latest nD visualization. I found a way to put the hiding box on top of everything (parameter zorder). Then the box can be drawn in background color. I mean the second box around the buffered data is not necessary any more. Here are my changes and the resulting effect:


![Image](https://user-images.githubusercontent.com/79243976/208379186-b707be2d-fd17-45da-bd59-dac31b772dcd.png)


![Image](https://user-images.githubusercontent.com/79243976/208379282-97611fae-f3d9-495d-a2b1-c9b5d8aacc77.png)


What do you think of this?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , wow this is cool. This looks even better.

The idea to keep the box around the buffered data, was if someone wants to plot them in different color through external p_settings parameter, the dimensions of the box will be determined within the window script.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I just had another thing, to maybe discuss in a meeting, shall we add instance ids while we instantiate instances. Currently the plots work with independent id generation. I mean, the ids are generated in plot methods and incremented at every run. But a window, or outlier might remove data within the wf irrespective of their order. 
Currently, I also remove the data, at the first position in the plot data.

**Comment by detlefarend** [comment]
> Hi @detlefarend , wow this is cool. This looks even better.
> 
> The idea to keep the box around the buffered data, was if someone wants to plot them in different color through external p_settings parameter, the dimensions of the box will be determined within the window script.

Sry I fear I didn't get the idea of this box.

What do you think of a dotted thin vertical line to mark the end of the buffer before it's getting blurry. On bg<> black it could be black and white otherwise.

**Comment by detlefarend** [comment]
> Hi @detlefarend , I just had another thing, to maybe discuss in a meeting, shall we add instance ids while we instantiate instances. Currently the plots work with independent id generation. I mean, the ids are generated in plot methods and incremented at every run. But a window, or outlier might remove data within the wf irrespective of their order. 
> Currently, I also remove the data, at the first position in the plot data.
> 

Definitely a good idea. Let's do this. I think it's an improvement within class Stream... Do you want to take over?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I just found a small thing. The hiding box is a bit too big:

![Image](https://user-images.githubusercontent.com/79243976/208751341-f10f38b6-24a4-4772-8d21-875290b419d6.png)

Maybe two options: 
1) Make it a bit smaller (question is: how much smaller?)
2) Plot a boundary around the box in the same color as the ax (advantage: we have a better visual separation of obsolete and buffered data)

**Comment by laxmikantbaheti** [comment]
I think the second option. 
Shall I do that?

**Comment by detlefarend** [comment]
I would also prefer this. Let's give it a try...

By the way: I added further howtos due to the 2D/3D plotting. However, howto 005 (former 003) still raises an exception...

**Comment by laxmikantbaheti** [comment]
> By the way: I added further howtos due to the 2D/3D plotting. However, howto 005 (former 003) still raises an exception...

Hi @detlefarend , I checked it, this is caused because of my latest changes with initialization of boundaries 😅. I'll once check why I had kept [0,0] initially.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , this error is raised in specific cases. I don't know what it is yet, but it is raised while setting the axes limits in stream/models

**Comment by detlefarend** [comment]
Ok, I'll take a look tomorrow morning. Cool progress today☺️👍

**Comment by laxmikantbaheti** [comment]
I had fun 😁

**Comment by detlefarend** [comment]
Hi, I saw that you added a frame to the hiding box. Two annotations: please try to use the color of the surrounding ax box instead of statically using black. Second, please remove the commented code as far as it is not needed. Thx!

**Comment by detlefarend** [comment]
Looks good. Thank you!

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I changed the logic of linking a task to the plot settings of the predecessor. Now task window is switched to a different view, but raises errors in 2d/3d. I am a bit too tired today to analyze it further. Maybe you can take a look in the next days. Can be reproduced by howtos oa_pp_003, 004...

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I checked it, this is happening because, once ethe axis type is changed, let's say to 2D, the _init_plot_2D is not called. The update_plot_3D is called but the plot is not initialized for that specific view.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, thanks for taking a look. I figured that it's rather a problem in the framework than in specific task code. I can take over again.

**Comment by laxmikantbaheti** [comment]
hi @detlefarend , for now, I just refactored the window, it works for both 2d and 3d. Can you please take a look and let me know if it is behaving correctly?
Thank you!

**Comment by detlefarend** [comment]
Nice!

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I refactored/optimized the default visualization of stream tasks and the id generation of instances. I assume that I found a bug in class Windows. If p_delay is True and the buffer is full then the buffered instances are not forwarded in the order they were buffered. I guess the problem is around line 185. Instead of this you need to implement a ring buffer logic to fill p_inst_new. Howto 110 shows the problem....

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , since the buffer is full for the first time before forwarding the instances, the instances are exactly at the same position as their ids.  The p_inst_new for window are  forwarded with correct instance order. However, when debugged it, I found that when the following task (Custom t2 in this case) takes instances from from window instances, it updates its instances using update() method, which is taking the instances randomly irrespective of their order in predecessor's list.  This is visible if we put a breakpoint at line 237 in models.py.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, thanks for your helpful analysis! I solved the problem by refactoring StreamShared.get_instances(). Btw: as mentioned yesterday I also refactored the (stream) plotting and I was able to speed it up by factor >= 2.

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, thanks for your helpful analysis! I solved the problem by refactoring StreamShared.get_instances(). Btw: as mentioned yesterday I also refactored the (stream) plotting and I was able to speed it up by factor >= 2.

The plots have become significantly fast now, even in my local pc. Is it because plt.ioff()

**Comment by detlefarend** [comment]
> > Hi @laxmikantbaheti, thanks for your helpful analysis! I solved the problem by refactoring StreamShared.get_instances(). Btw: as mentioned yesterday I also refactored the (stream) plotting and I was able to speed it up by factor >= 2.
> 
> 
> 
> The plots have become significantly fast now, even in my local pc. Is it because plt.ioff() 

Yes, this was the main speedup factor.
