### ISSUE TITLE
Bug: Howto BF-STREAMS-011 fails after River update

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#456]
**1 Describe the bug**
The howto/wrapper is not compatible to the current River version 0.13.0. 

**2 To Reproduce**
Just update River and run the howto.

**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [x] Windows
   - [x] Mac OS

**Comment by laxmikantbaheti** [comment]
hello @detlefarend ,
the howto is running for river 0.10.1 
I tried to uodate the river version, but it seems like 0.10.1 is the recent one.

**Comment by detlefarend** [comment]
Hi Laxmikant, River is on 0.13.0. Try `pip install river --upgrade`. Seems that they did incompatible changes. In that case we should adapt the wrapper to the latest version and set the minimum version. See #370.
