### ISSUE TITLE
BF-MT : Dropped Connection on BaseManager Socket due to a lot of request

### ISSUE THREAD

**Issue by rizkydiprasetya** [fhswf/MLPro#464]
**Description/Motivation**
Connection dropped by the socket connection from BaseManager due to a lot of connection request. 

Further checks, this happens currently only on Mac. I have checked our Ubuntu server, it works fine.

**Current Temporary Solution**
Change the backlog number of the socket listener.

**OS and Specification**
- Mac M1 Pro

**Cross references**
https://github.com/python/cpython/issues/88321

**Comment by detlefarend** [comment]
As discussed today: we add an annotation/cross reference for this to the related bf.mt howto.001
