### ISSUE TITLE
Bug: RTD Autodocumentation of API modules missing

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#468]
**1 Describe the bug**
In appendix 2 of the current online documentation the technical class documentation is missing. In opposite to this, after local sphinx-autobuild of branch main all descriptions exist. It seems that there is still a difference between local autobuild and workflow during merge to main.

**Comment by detlefarend** [comment]
@rizkydiprasetya Would be nice if you could take a look. Thank you!

**Comment by rizkydiprasetya** [comment]
@detlefarend I changed something. Could you please check again? The workflow is not optimized yet but it should work. I will optimize it later.

**Comment by rizkydiprasetya** [comment]
./doc/rtd/_build is included in .gitignore, so shouldnt be matter. And the building process is in RTD side. So we send the raw rst to RTD, and they will build the rst into html in their side. I have to check again the configuration, and the building logs from rtd.

**Comment by rizkydiprasetya** [comment]
@detlefarend its there now. Remove cache browser and you should get the new one.

![Screenshot 2022-10-18 182919](https://user-images.githubusercontent.com/75730306/196489306-18f3c59e-11f5-4351-bfc9-3d82a3a6f2ce.png)

![Screenshot 2022-10-18 182945](https://user-images.githubusercontent.com/75730306/196489314-5084fa44-ec16-478d-ba82-ef46082d3a1e.png)

**Comment by detlefarend** [comment]
Yep! It's there. Thank you for checking👍
