### ISSUE TITLE
OA-Task: Normalizers

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#472]
**Description/Motivation**
Adaptive normalizers for MLPro-OA
**Task list**
- [x] 1. A new pool object mlpro/oa/pool/tasks/normalizers.py
- [x] 2. class Noramlizer (cancelled in design)
- [x] 3. class NormalizerMinMax
- [x] 4. class NormalizerZTrans

**Related issues**
#245 #406 

**Branch**
online_adaptivity6

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I just prepared this issue to have a container for discussions. One important aspect is here, that all normalizers should have the optional feature to duplicate incoming instances and normalize/forward the duplicate and not the original data. This is necessary in the case that a predecessor window task buffers the original data. These must not be changed. 

I propose to implement this logic in the _run() method of the normalizer base class. Child classes can call the super-method in their own _run() methods. To this regard, I just added a parameter p_duplicate_data to the constructor of class Normalizer (class diagram only). Perhaps this is a more fundamental feature that should be added to class OATask, method run()... Yes, I think so...

**Comment by detlefarend** [comment]
I've placed the logic of duplicating data at the classes OATask/OAWorkflow. You don't have to care for it. The normalizers can just normalise the incoming data directly.

**Comment by laxmikantbaheti** [comment]
![image](https://user-images.githubusercontent.com/100450659/197233897-c2ed3f3b-0af1-42c4-be3a-65e73a8e5a44.png)

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti could you please refactor the classes after our changes of the day (set -> list)?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I found a gap in NormalizerMinMax: on the first run it raises an exception because the norm parameters are not initialized. See howto 003.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, howtos oa_pp_003-005 are running now. But there is a remaining problem with the normalizer: if you turn of the p_delay of task Window then it raises an exception. I guess it's an initialization problem, if it get's just one first instance... Could you please take a look?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , do you mean this error?
![image](https://user-images.githubusercontent.com/100450659/209951206-031edf5b-72ad-4d65-8801-94b4a0603be1.png)

**Comment by detlefarend** [comment]
Yep

**Comment by laxmikantbaheti** [comment]
> Yep

Hi @detlefarend , the bug is fixed in bf_stream

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, I already merged it to oa10. It looks good.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, a further challenge regarding the default visualiation. Instances to be removed are currently not found by this 'sharp' point search. I have currently no better idea than to do a full scan of the x-data list to identify a point close enough, then comparing y/z as well. This will take runtime resources...

![Image](https://user-images.githubusercontent.com/79243976/209979564-bdd4708e-6e18-41ab-8aa0-df98782f4d29.png)

**Comment by laxmikantbaheti** [comment]
Done with the renormalizing of obsolete data..
