### ISSUE TITLE
Bug: Howtos RL-WP-001/002/003 are logging in unit test mode

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#473]
**1 Describe the bug**
The howtos mentioned log in unit test mode.

**2 To Reproduce**
Build the rtd documentation locally and redirect the output to a file. In the file the log outputs are shown up.

**Comment by steveyuwono** [comment]
Hi Detlef, I will be out of the office from tomorrow until Monday. I will figure this out afterwards if it is fine for you.

**Comment by detlefarend** [comment]
Hi Steve, thanks for the information. It's absolutely not urgent.
