### ISSUE TITLE
Ongoing validation of all wrappers

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#489]
**Alternative 1 (static)**
Class Wrapper is extended by a new constant C_VALID_VERSION. It contains the highest version of the related package that was explicitely validated by the MLPro team. If a higher version is installed a hint shall be logged that a proper operation is not guaranteed.

**Alternative 2 (generic)**
Unit test class for each wrapper with a representative and meaningful test case. Name and version of a successfully tested package are logged in a file. The file is linked in the rtd documentation. Regarding test cases: probably the related howtos can be called. The test failed if a howto raised an exception. Maybe the generated list of packages/versions can be uses for the complete installation of mlpro.

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, what do you think of alternative 2? Nice teckie task, isn't it?

**Comment by rizkydiprasetya** [comment]
Closing this, not necassary.
