### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#490]
**Preparation**
- [x] Appointment scheduled? Room booked?
- [x] Attendees informed?

**Agenda**
- [x] **Review/close of current sprint**
- [x] **Planning of next sprint**
  - [x] Review of unassigned issues
  - [x] Review/agreement of workload of collaborators
  - [x] New sprint planning issue
- [x] **Special topic # 1: BF-Plot: New plot systematics (Detlef)**
- [x] **Special topic # 2: BF-Streams - Stream processing in MLPro (Detlef)**
- [x] **Special topic # 3: Recent refactoring activities (Detlef)**
- [x] **Special topic # 4: BF_Math - Transfer Function - still provisional (Steve)**
- [x] **Special topic # 5: MuJoCo Integration (Rizky)**
- [x] **Check: decisions documented?**

**Comment by detlefarend** [comment]
We should talk about the latest extensions of the plot systematics (class bf.plot.Plottable). I added it to the agenda. Please add your topics on demand.

**Comment by detlefarend** [comment]
Hi colleagues, please add your special topics until end of November.

**Comment by steveyuwono** [comment]
Hi @detlefarend, I forgot to inform you that I will be in Indonesia from 26th Nov until 20th Dec. Can we shift the sprint meeting to one week earlier, which means 25th Nov? Otherwise, I can skip the next sprint planning or join it via zoom.

**Comment by detlefarend** [comment]
Hi colleagues, thanks for the update. I re-scheduled to the 25th of November as zoom meeting. Great to hear that you both are vacationing soon. My request is that in the remaining time we coordinate well and focus on the points relevant to v1.0.0.

There is one special topic I would like to push this year: to reduce the scope of MLPro to pure ML functionalities and to place/shift higher and more specific functions to extension repos. Definitely worth to discuss f2f and we have already an appointment for this. It's currently Nov. the 18th 3-5 p.m. but we can turn it to a real workshop where we make decisions and start doing it. In that case we could start 1 p.m..

**Comment by steveyuwono** [comment]
> Hi colleagues, thanks for the update. I re-scheduled to the 25th of November as zoom meeting. Great to hear that you both are vacationing soon. My request is that in the remaining time we coordinate well and focus on the points relevant to v1.0.0.
> 
> There is one special topic I would like to push this year: to reduce the scope of MLPro to pure ML functionalities and to place/shift higher and more specific functions to extension repos. Definitely worth to discuss f2f and we have already an appointment for this. It's currently Nov. the 18th 3-5 p.m. but we can turn it to a real workshop where we make decisions and start doing it. In that case we could start 1 p.m..

Okay perfect, thank you!

**Comment by detlefarend** [comment]
We decided to set up the new class FctSTrans as a new base class for rl.AFctSTrans, MuJoCo wrapper and MLPro-MPPS extension.
