### ISSUE TITLE
RL: Double Pendulum - New plot systematics

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#497]
After extension of class bf.plot.Plottable some changes are to be made to follow the new systematics:

- [ ] Constructor: new parameter p_visualize
- [ ] Rename init_plot() and update_plot() to _init_plot_nd(), _update_plot_nd()
- [ ] Attribute C_PLOT_DEFAULT_VIEW = Plottable.C_PLOT_VIEW_ND
- [ ] Validation of related howtos

**Comment by detlefarend** [comment]
@laxmikantbaheti I'll take over this part...

**Comment by laxmikantbaheti** [comment]
Ok, thank you.
