### ISSUE TITLE
Bug: Howto RL-WP-003 (Multi-agent/PettingZoo) - Visualization fails

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#499]
**1 Describe the bug**
After refactoring of the howto and the pettingzoo wrapper the visualization of the pettingzoo env fails. It seems that there is a problem with pettingzoo and/or gymnasium...

**2 To Reproduce**
Run the howto.

**3 Expected behavior**
Proper visualization of pettingzoo environment pistonball_v6

**4 Screenshots**
![grafik](https://user-images.githubusercontent.com/79243976/199294706-1db3e12d-efb2-4ff2-bc24-22d42ea19826.png)

**5 Additional Informations**

5.1 Operating System
   - [X] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by rizkydiprasetya** [comment]
This can be solved by putting the default render_mode on the initialization of the environment.
 `zoo_env             = pistonball_v6.env(render_mode="human")`
