### ISSUE TITLE
BF-Streams: Class Stream as Python iterator

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#507]
Currently class Stream can't be used as an iterator. To solve this the class definition is to be changed as follows:

- [x] Replace method reset() by __iter__()
- [x] Replace method get_next() by __next__()
- [x] For optional seeding a separate method set_random_seed() is needed
- [x] Modification/validation of related wrappers
   - [x] OpenML
   - [x] River
   - [x] Scikit-learn
- [x] Modification/validation of related howtos
   - [x] OpenML
   - [x] River
   - [x] Scikit-learn

**Cross references**
https://www.w3schools.com/python/python_iterators.asp

**Comment by detlefarend** [comment]
@laxmikantbaheti fyi

**Comment by laxmikantbaheti** [comment]
Yes, makes it more easier to use. This is very good. I think many popular sources like pytorch also uses datasets as iterators.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I refactored class Stream and wrapper OpenML and the related howto. Could you perhaps take over the according steps for River and Scikit-learn? If you have time please add yourself as assignee. Otherwise I'll continue with this next week.

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti forget my last post. I'll take over again...

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti forget my last post. I'll take over again...

Hello, sorry I couldn't make room for this in the last week.

**Comment by detlefarend** [comment]
Absolutely no problem;)
