### ISSUE TITLE
README.md: New badge for Anaconda downloads statistics

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#516]
In #494 new badges for PyPI download statistics were added. A badge for Anaconda is also available but the problem is that it currently can't be customized (own text and colors). This shall be validated periodically and incorporated as soon as customizing is possible.

Origin link:
https://anaconda.org/mlpro/mlpro/badges/downloads.svg

Customized link:
https://anaconda.org/mlpro/mlpro/badges/downloads.svg?left_color=blue&right_color=orange&left_text=Anaconda%20Total%20Downloads

See also:
https://anaconda.org/mlpro/mlpro/badges

**Comment by rizkydiprasetya** [comment]
@detlefarend do we really need own text and colors?

**Comment by detlefarend** [comment]
@rizkydiprasetya no we don't. But it should be a senseful text like "Anaconda.org Total downloads". Otherwise no one knows whtat's the sense of this badge. Independently to this, the counter is 0. This is wrong or outdated because you and Steve told me that you were able to install by using conda. This should have updated the counter?
