### ISSUE TITLE
BF-Streams: Provider specific stream options

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#518]
Specific stream providers support specific stream options. To this regard, class bf.streams.Stream shall be extended by a new method set_options.

- [x] **New method Stream.set_options()** (Detlef)
- [x] **Extension of wrapper OpenML** (Detlef)
- [x] **Extension of howto 051** (Laxmikant)
- [x] **Review**

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti my part is done. Howto can be extended as discussed.

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , the openml wrapper needs some further refactoring in OpenML wrapper. Currently the label data is set by a constant from openml, and that data is popped out of the array, but now with this target variable the arrays are already split. Shall I make the changes?

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I would like to review this because now the wrapper supports parameter targed only. Let's take a look together next time...

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti I just made a further small adjustment on OpenML wrapper due to stream options.
