### ISSUE TITLE
MLPro-Extension: MPPS

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#528]
A new MLPro extension shall be created.

**1 GitHub repository** 
**1.1 Name:** fhswf/mlpro-mpps
**1.2 Template:** fhswf/mlpro-extension

**1.3 Privacy level**
   - [X] **Private**
   - [ ] **Public**
         Please note: publication of code related to research topics of FAT needs the approval of Prof. Schwung! 
        - [ ] Binaries only (.pyc)
        - [ ] Open source

**1.4 Administrators:** @steveyuwono 

**2 Topic**
A module for designing, simulation, or controlling a production system.

**3 Key features**
- Base classes for industrial components and their processes (sensors, actuators)
- Transfer functions?
- Base classes for connecting those components (module/station)
- Base classes to build a modular production system
- Enable usage for simulation and hardware control
- Ensure they can be used not only as RL Environment but also as for general use

**4 Origin of the code**
- [ ] New 
- [X] Extraction of existing MLPro code (please enumerate below)
      (The approval of all MLPro administrators is needed! Please assign.)
      mlpro.rl.pool.envs.sim_mpps

**5 Annotations**
...

**Comment by detlefarend** [comment]
Hi @steveyuwono @marlonloeppenberg please take a look and complete the issue. If you have doubts about the scope or a need for futher discussions then let's schedule an appointment.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono @marlonloeppenberg please take a look and complete the issue. If you have doubts about the scope or a need for futher discussions then let's schedule an appointment.

I will have a meeting with Marlon next Wednesday to talk about the direction of this MPPS and also what should be included and excluded. After our previous meeting and this Friday's meeting, I hope we could already get a general idea of the scope and structure of the MPPS in the MLPro-Extensions. But I will inform you once an additional discussion is necessary

**Comment by steveyuwono** [comment]
Repo is created and I also added both of you and Rizky as admins. We will continue the works related to MPPS to the new repo
