### ISSUE TITLE
RL: Extensions on Double Pendulum

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#536]
As discussed in our today's meeting:

**1. Extensions on rewarding**
- [x] New parameter p_rst_balancing
- [x] New parameter p_rst_swinging
- [x] Constants for valid reward strategies for balancing
- [x] Constants for valid reward strategies for swinging
- [x] Internal dictionary to store reward_methods for state area (balancing/swinging)
- [x] New reward strategy for balancing including old/new state

**2. Extensions on start position**
- [x] New optional parameter for boundaries of random start position
- [x] New optional parameter for boundaries of balancing state area

**3. Further extensions**
- [x] New boolean parameter: break when leaving the balancing state area
- [x] New optional horizon parameter for reward plot (if > 0 then this number of cycles is shown in the plot
- [x] New optional boolean parameter for an additional trend line
- [x] New optional parameter for state component weights (Postponed!)

**4. Documentation**
- [x] Howto1 with random agent
- [x] Howto2 for manual env validation
- [x] RTD: Description of env and howtos

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, it seems that this issue is done so far. Can we close it?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend yes the marked tasks are done. The weighted state space is yet to be implemented.

It's also true that this wouldn't take a lot of time. I just lost it in other issues. Shall I quickly finish this and close the issue?

**Comment by detlefarend** [comment]
Hi @laxmikantbahet, sure. Would be good👍

**Comment by laxmikantbaheti** [comment]
Done.
