### ISSUE TITLE
Incident: Workflow after commit takes > 1h

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#537]
Since yesterday evening we have a huge delay in the GitHub workflows after commit...

**Comment by detlefarend** [comment]
@rizkydiprasetya I guess I found the error. It's a problem with a specific OpenML data set... Our turn.

**Comment by rizkydiprasetya** [comment]
You can check to test it locally. Because currently it stuck on test script. You can always do the test local first.

**Comment by detlefarend** [comment]
See my latest updates on this item.

**Comment by rizkydiprasetya** [comment]
What should I do here?

**Comment by detlefarend** [comment]
> What should I do here?

Sorry, it's still our/my part. Yesterday I checked our latest changes and howtos and even the doc build but everything seemed fine. That's why I reassigned to you to also take a look. I started writing a comment when I got the idea to push an empty commit on main. There the unit tests run as usual. So the problem is obviously in my stream branch. I cancelled commenting but forgot to assign back to me.

**Comment by rizkydiprasetya** [comment]
Its the how_to_bf_010 with openml. I did check, but I thought you already know where the problem is. There is another pull request called "cc" just to check the action without openml. It works fine, and finished under 10 minutes.

**Comment by detlefarend** [comment]
Am I right, that you cloned branch cc from main? The problem occurs in bf_streams since Friday evening (unit tests after performing an empty commit on main were more or less ok (~18m)). In bf_streams I renamed/refactored the stream howtos. I tested them several times and they terminated in a moderate time. But your last post made me check the references to the howtos in the rtd. I found that they were outdated. I just updated rtd but the unit test after commit is currently still ongoing (>18m).

I have a problem on my PC that avoids me from running the ut's locally. It's about the RobotHTM env. It needs package transformations but I am not able to install it because of a c level problem:

![grafik](https://user-images.githubusercontent.com/79243976/202995271-7dbd939c-d76a-45c5-bc99-a2f87a723197.png)

Do you know the problem and the solution?

**Comment by rizkydiprasetya** [comment]
sudo apt install python3-dev

**Comment by detlefarend** [comment]
no effect:-(

**Comment by rizkydiprasetya** [comment]
Then I dont know, because normally it is missing the python3-dev. 

You dont actually need to test all of them. Just the bf_stream with openml. Because the rest of the example works fine. Eve I run locally, it takes time. You can have a look on https://github.com/fhswf/MLPro/actions/runs/3508848404/jobs/5877547068
This run is from the cc branch. It stucks there in bf 010 open ml

**Comment by rizkydiprasetya** [comment]
Here is more detail:

- This is the last commit that workflows ran under 6 minutes : https://github.com/fhswf/MLPro/pull/514/commits/2f2d51fe1e092dac56b53a0b382fe455ee62efdd

- After this commit, the workflows ran for more than 30 minutes : https://github.com/fhswf/MLPro/pull/514/commits/33e529b11fe2807f3e67e2743e14c904ff2c72ff

**Comment by detlefarend** [comment]
Analyzing main/cc makes no sense any more because I/we changed many things in bf_streams. The main problem is the delay of rtd build. It takes 42m. But yes, the howtos are running too long as well (14m)...

**Comment by detlefarend** [comment]
Please lets just talk about bf_streams. The stream implementations in main are outdated.

What exactly do you mean with "exclude"? Commenting in test_examples? I already tried this. But this doesn't affect the delay in rtd build...

**Comment by rizkydiprasetya** [comment]
Delete the howto file.

**Comment by detlefarend** [comment]
Ok, I renamed howto_bf_stream_051 (-> openml). It's running.

But I absolutely don't understand why it should help. The howto run's bright in < 1 min and dark <10sec. The rtd build runs locally roundabout 1-2 min...

**Comment by rizkydiprasetya** [comment]
I dont understand what do you mean by bright and dark. For RTD did you delete your build folder?

**Comment by detlefarend** [comment]
Sry. By bright I mean running it manually with logging and so on. Dark means I run it manually with the unit test settings (by changing the code line `if __name__ == "__main__"`.

Yes, I deleted the folder before building rtd.

**Comment by detlefarend** [comment]
In the current run the rtd build is ongoing since 14min... The problem is that you can't see in the logs where exactly the time is comsumed:-(

**Comment by rizkydiprasetya** [comment]
check this : https://github.com/fhswf/MLPro/pull/539

This is cloned from bf_streams, and I deleted all related to openml in rtd and howto. It works fine and ran under 10 minutes. The reason is the autodoc will check all the examples. So thats why even if you renamed it, it will be autodetected under bf.examples. That is why, I asked you to delete it. 

So, here there two questions, do we really need to autodoc all the howto? or just some of it? Because autodoc will access the howto with openml which takes very long time to be executed.

**Comment by detlefarend** [comment]
But after renaming the howto all references in rtd should fail, right? However,...

I am going to locate the causing code passage. Currently I guess, that it's a kind of routing/network problem during downloading the stream data from openml. I know this behaviour from various streams they provide. If they are not available it takes much time until openml runs into a timeout. On my PC the routing is ok because I can't reproduce the delay...

**Comment by rizkydiprasetya** [comment]
I dont know either, I have fast internet but still the code is running forever like 15 minutes plus on local.

**Comment by detlefarend** [comment]
Did you try to run the howto manually?

**Comment by rizkydiprasetya** [comment]
yep, with the same configuration as imported module.

**Comment by detlefarend** [comment]
How long does it run? Could you please run it in the debugger step by step and let me know when it starts delaying?

**Comment by rizkydiprasetya** [comment]
is it ok if I do it after lunch?

**Comment by detlefarend** [comment]
Sure! Thanks for your support!!

**Comment by rizkydiprasetya** [comment]
Here where the code takes more time :
https://github.com/fhswf/MLPro/blob/88598c7ac249ddcaab3dd3bc27569c92313287af/src/mlpro/wrappers/openml.py#L303

Here is the execution time on my local :
<img width="536" alt="Screenshot 2022-11-22 at 07 56 48" src="https://user-images.githubusercontent.com/75730306/203251319-6513480e-a804-4e49-83db-91eb39422a46.png">

**Comment by detlefarend** [comment]
That's interesting. On my pc and laptop it takes <5sec...

**Comment by detlefarend** [comment]
I think the remaining delay is caused by the rtd makefile in relation to the shadow appendix 4. If not necessary, I propose to remove it but I am a bit insecure about removing the right things in the rtd makefile. Did you set up this logic in the past or was it William?

![image](https://user-images.githubusercontent.com/79243976/203292299-c4f0921e-e3fb-4335-bee9-7509bc7f4890.png)

**Comment by rizkydiprasetya** [comment]
> That's interesting. On my pc and laptop it takes <5sec...

In my office PC, it takes also around 15 minutes.

> I think the remaining delay is caused by the rtd makefile in relation to the shadow appendix 4. If not necessary, I propose to remove it but I am a bit insecure about removing the right things in the rtd makefile. Did you set up this logic in the past or was it William?
> 
> EDIT: You mean (slack) that this is for building this extra pdf documentation? If yes: please remove it for now and put a hint in the related issue #419.
> 
> ![image](https://user-images.githubusercontent.com/79243976/203292299-c4f0921e-e3fb-4335-bee9-7509bc7f4890.png)

I dont know, one of you have the idea to generate all the api with acidic from sphinx. So, its your call.

**Comment by detlefarend** [comment]
> > That's interesting. On my pc and laptop it takes <5sec...
> 
> In my office PC, it takes also around 15 minutes.
> 
> > I think the remaining delay is caused by the rtd makefile in relation to the shadow appendix 4. If not necessary, I propose to remove it but I am a bit insecure about removing the right things in the rtd makefile. Did you set up this logic in the past or was it William?
> > EDIT: You mean (slack) that this is for building this extra pdf documentation? If yes: please remove it for now and put a hint in the related issue #419.
> > ![image](https://user-images.githubusercontent.com/79243976/203292299-c4f0921e-e3fb-4335-bee9-7509bc7f4890.png)
> 
> I dont know, one of you have the idea to generate all the api with apidoc from sphinx. So, its your call. And you can just remove the entire line (20th)

I never added something to this makefile. If you don't know about this special line I guess it was an early try from William. No one else has worked on the build systematics. However, I'll remove the line and appendix4.

**Comment by detlefarend** [comment]
It's running 5m w/o the appendix4 stuffs...

**Comment by rizkydiprasetya** [comment]
@detlefarend with openml?

**Comment by detlefarend** [comment]
Unfortunately not:-( I have created an issue for the follow-up... I guess I'll contact them and report the problem.
