### ISSUE TITLE
Meeting: Online Adaptive Systems (16-12-2022)

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#556]
**Before the meeting**
- [x] Agenda prepared
- [x] Room or Zoom prepared
- [x] Attendees invited

**Agenda**
1. MT gap
    In asynchronous workflows then subsequent tasks are started by raising an event. In that case, the modified instances of the predecessor tasks are not stored in the shared object.
2. Visualization of stream tasks
   - StreamTask, default implementation: how to deal with instances to be removed
   - Specific plot settings for features, labels, ...
   - Window: nD, 2D, 3D view; how to highlight the buffered data
   - Boundary Detector: nD, 2D, 3D
3. Method StreamTask.run(): instances as lists or sets?
4. Adaptive environments

**Preparation**
...

**Related issues**
...

**After the meeting**
- [x] Decisions documented
- [x] Next steps defined

**Comment by detlefarend** [comment]
Solution for the MT-gap:
We introduce a new attribute C_CUSTOM_RUN_MTHD in class bf.mt.Task. This custom_method is called in method _run_async(). It is predefined with self._run. In class StreamTask we introduce a further method _run_extended() that calls custom method _run() and stores the result instances in the so...

**Comment by detlefarend** [comment]
Class StreamTask: extension of default visualization: instances in p_inst_del need to be removed from the plot data structure. (Laxmikant takes over)

**Comment by detlefarend** [comment]
Topic 3: We decided to turn the type of parameters p_inst_new, p_inst_del to lists again. (Detlef)

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, the MT-gap is solved and topic 3 is also done. Level bf.streams is cleaned up: tasks window and rearranger and all related howtos are running again. For your extension on class StreamTask I add a comment in the related task.
