### ISSUE TITLE
BF-Streams: Native stream "Moving noisy point clouds"

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#561]
Two new native streams shall be implemented (2D/3D). Both generate a defined number of noisy point clouds - similar to the existing streams **cloud2d_static.py** and **cloud3d_static.py**. In opposite to the static derivates, the centers shall move over the time. Some of the clouds shall merge.

**To do**
- [x] **1. MovingClouds2D ("Moving noisy point clouds 2D")**
       - [ ] New module mlpro.bf.streams.streams.cloud2d_dynamic.py
- [x] **2. MovingClouds3D ("Moving noisy point clouds 3D")**
       - [ ] New module mlpro.bf.streams.streams.cloud3d_dynamic.py
- [x] **3. Basic validation in mlpro.bf.examples.howto_bf_streams_001_accessing_native_data_from_mlpro.py**
       Nothing special to do. The howto should automatically detect new native streams and access their instances
- [x] **4. New howtos 2d/3d that visualize the dynamic behavior of the clouds**
- [x] **5. Extensions on RTD**

**See also**
mlpro.bf.streams.streams.cloud2d_static.py
mlpro.bf.streams.streams.cloud3d_static.py

**Related branch**
online_adaptivity12

**Comment by detlefarend** [comment]
Hi @syam47, I enabled you to contribute actively and assigned this issue to you. Please don't hesitate to contact me if you have any questions. Welcome to MLPro!

**Comment by syam47** [comment]
Thank you. I'll be in touch with you.

**Comment by detlefarend** [comment]
Hi @syam, I just took a look at your implementation. At first: the code looks very clean! I just found a typo in the module name of the howtos: "visuali**z**ation" instead of "visuali**s**ation".

I think the performance could be increased. **Howto_bf_streams_001** shows that the throughput of the dynamic streams is roundabout a third of the static derivates (under Ubuntu Linux). I guess that we can nearly reach the same throughput. Maybe you could review your implementation to this regard.

![Image](https://user-images.githubusercontent.com/79243976/228276914-1c2d7495-217a-4092-a377-d1db881c83fc.png)

Thank you for contributing to MLPro!

**Comment by syam47** [comment]
Thank you for the feedback. I'll work on speeding up the code.

**Comment by syam47** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/125185368/228585580-d943237d-7fa7-487c-87d9-752ae3272a48.png)
I have made some changes to the files. Now I'm getting significant changes in the throughput. Could you take a look at them?

**Comment by detlefarend** [comment]
> ... I have made some changes to the files. Now I'm getting significant changes in the throughput. Could you take a look at them?

Nice! Now your dynamic clouds outperform the static ones. Maybe I should check my code now:-D

**Comment by detlefarend** [comment]
new branch: bf_updates

**Comment by syam47** [comment]
All tasks completed.

**Comment by detlefarend** [comment]
Hi @syam, I just reviewed it. Here are my findings:

- Howtos 003/004 don't have a dark mode (see https://github.com/fhswf/MLPro/tree/main/templates)
- Typo in the name of the howtos (and all references in RTD): visuali**s**e
- Streams: please add constants for possible values of parameter p_pattern
- Streams: please add a further parameter for the variance

@syam, @laxmikantbaheti: could you please rearrange the single streams in a sub-folder and separate rst files? And please add the related howtos as cross references there. Thank you very much!

**Comment by laxmikantbaheti** [comment]
Hi, I think there is a bug in the visualization of dynamic clouds, cause it plots while building the rtd.
Probably, the dynamic stream class does not have a p_visualize parameter...

**Comment by syam47** [comment]
I will look into them asap. I might need some help from Laxmikant.

**Comment by laxmikantbaheti** [comment]
> I will look into them asap. I might need some help from Laxmikant.

Sure,  let me know how I can help you..

**Comment by syam47** [comment]
> Hi @Syam, I just reviewed it. Here are my findings:
> 
> * Howtos 003/004 don't have a dark mode (see https://github.com/fhswf/MLPro/tree/main/templates)
> * Typo in the name of the howtos (and all references in RTD): visuali**s**e
> * Streams: please add constants for possible values of parameter p_pattern
> * Streams: please add a further parameter for the variance
> 
> @Syam, @laxmikantbaheti: could you please rearrange the single streams in a sub-folder and separate rst files? And please add the related howtos as cross references there. Thank you very much!

I have updated the codes as well as RTD, taking into account the mentioned findings. Please review my changes and let me know if there is anything else that needs to be addressed. @detlefarend

**Comment by syam47** [comment]
> Hi, I think there is a bug in the visualization of dynamic clouds, cause it plots while building the rtd. Probably, the dynamic stream class does not have a p_visualize parameter...

Updated the codes with the visualize parameter. Now the bug seems to be resolved. Thank you. @laxmikantbaheti

**Comment by detlefarend** [comment]
Hey ho @syam47, I checked the howtos. The behavior in batch mode and the new parameter p_variance works well. There is a problem with seeding. Background: to gain reproducible random behavior we introduced method **set_random_seed** in class **Stream**. It works properly for the native Python standard random generator. If you use a different generator (e.g. numpy, ...) the method mentioned needs to be redefined. I added a seeding line in both howtos to check this. Could you please take a look? The goal is to have exactly the same random behavior whenever/wherever the programs are started. If this works you could "play" a bit with the seeding value to gain a "beauty" cloud distribution in the howtos.

Then a question: is it easily possible to add a further parameter for the velocity of center movement? I would like to control the average density of a moving cloud with it. And maybe a further parameter for the number of clouds? If you have further ideas to parameterize the behavior then just add it. It makes sense to improve especially these two streams because the will be important benchmark streams for clustering and anomaly detection.

@syam47, @laxmikantbaheti RTD is much better. Thank you for restructuring!

**Comment by syam47** [comment]
Yes, I will work on your suggestions. @detlefarend

**Comment by detlefarend** [comment]
Update (in our today's sprint planning): 
- random seed is solved
- new parameter for the number of clouds is low effort
- new parameter for the velocity of the centroid is higher effort -> to be discussed Detlef/Syam

**Comment by syam47** [comment]
New parameter for the velocity of the centroid has been added. Please review.. @detlefarend
