### ISSUE TITLE
Bug: howto rl_agent_005 and rl_wp_001

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#564]
**1 Describe the bug**
![image](https://user-images.githubusercontent.com/88610818/208898274-785a485e-19b5-4e13-a106-45942160ebca.png)

**2 To Reproduce**

**3 Expected behavior**

**4 Screenshots**

**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [x] Windows
   - [x] Mac OS

**Comment by rizkydiprasetya** [comment]
Both are running ok on my Mac.

**Comment by rizkydiprasetya** [comment]
Probably I havent update my local. I will check again later.
