### ISSUE TITLE
BF-Streams: Native Stream with user-defined statistical properties (Drifting)

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#568]
**Description/Motivation**
Deriving over the static version of Native Stream in #567, this implementation additionally takes parameters that define the behvior of the drift

**Task list**
To be further defined
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#567 

**Cross references**
...

**Comment by detlefarend** [comment]
See #718
