### ISSUE TITLE
Refact: RTD

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#584]
**Motivation**
A review of our current rtd document structure revealed the following issues:

1. Section titles in the menu bar can't be clicked directly

2. PDF export of the documentation not possible

3. An unnecessarily large and unwieldy menu bar on the left

    ![2023-01-17_10-05](https://user-images.githubusercontent.com/79243976/212855786-809e4b89-f8f3-4a94-b0de-eb1fd5338115.png)

To solve these problems the following refactoring steps are proposed:

**Steps**
- [x] **New structure of (blue) menu captions and real sections**
       Proposal:
       
       - Welcome to MLPro
           1 Introduction
           2 Getting Started
           
       - Basic Functions  
           3 MLPro-BF - Basic Functions
            
       - Machine Learning
           4 MLPro-SL - Supervised Learning
           5 MLPro-RL - Reinforcement Learning
           6 MLPro-GT - Game Theory
           7 MLPro-OA - Online Adaptivity
          
       - Appendices
           A1 - Examples
           A2 - API Reference
           A3 - Project MLPro 
       
- [x] **Auto numbering**

**Comment by detlefarend** [comment]
Hi @steveyuwono @rizkydiprasetya @laxmikantbaheti, I need your feedback for this because the further documentation steps depend on it. If you agree I can take over the basic restructuring. For this I need a freeze of all rtd activities. I propose the following proceeding:

1.  Freeze of all documentation activities
2. Creation of new branch rtd_v1.0.0
3. Merge current branches rtd_intro, rtd_bf to rtd_refact
4. Remove rtd_intro, rtd_bg
5. Restructuring as mentioned in rtd_refact
6. Approval by the team
7. Release for further documentation activities

After that all changes on rtd should be done just in this new and final branch rtd_v1.0.0...

**Comment by laxmikantbaheti** [comment]
Sounds good to me 👍🏼

**Comment by rizkydiprasetya** [comment]
Looks fine to me

**Comment by steveyuwono** [comment]
Same for me

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya @laxmikantbaheti @steveyuwono, refactoring is done. You can move on with documentation. Please check the links within floating text. Maybe some of them are invalid and need to be updated. Hope that it's not that much.

Btw: you need to `pip install sphinx_multitoc_numbering` to build the docu locally.

**Comment by rizkydiprasetya** [comment]
Don't forget to put it also on the requirements.txt for RTD.
