### ISSUE TITLE
Bug: Howto_oa_pp_005 shows odd behavior

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#592]
**1 Describe the bug**
After 50 instances the window task starts forwarding the buffered instances. Task t4 (minmax normalizer) should show six random curves then. Instead, the first 50 (0-49) instances follow just one random curve.

**2 To Reproduce**
Run howto_oa_pp_005_rearranger_window_bd_normminmax_nd.py

**3 Expected behavior**
Six random curves in the plot of task t4 (minmax normalizer) during the entire experiment.

**4 Screenshots**
![2023-01-23_17-52](https://user-images.githubusercontent.com/79243976/214101250-bae10a09-12e0-4006-84ac-4e30765eb8e4.png)

**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, do you have any idea about a possible reason?

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , shall I make changes in oa 10? or a new branch? cause, I think I need to reflect the changes also in qa 1.0.0

**Comment by detlefarend** [comment]
Hi @laxmikantbaheti, let's do corrections in qa1.0.0. New developments in oa11 (oa10 is removed).

**Comment by laxmikantbaheti** [comment]
Yes, sorry, oa11. So then, shall I merge back qa 1.0.0 in oa11 after corrections?

**Comment by laxmikantbaheti** [comment]
> Hi @laxmikantbaheti, let's do corrections in qa1.0.0. New developments in oa11 (oa10 is removed).

Yes, sorry, oa11. So then, shall I merge back qa 1.0.0 in oa11 after corrections?

**Comment by detlefarend** [comment]
Yes please. And before final release we will make a decision whether to merge oa11 to main.

**Comment by laxmikantbaheti** [comment]
> Yes please. And before final release we will make a decision whether to merge oa11 to main.

sure, thanks!
