### ISSUE TITLE
Bug: howto_rl_agent_005_train_and_reload_single_agent, reload fails

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#603]
**1 Describe the bug**
The model reload failes due to a problem with dill.

**2 To Reproduce**
1. Run the howto in branch quality_assurace_v1.0.0
2. Wait until model reload

**3 Expected behavior**
Proper control of cart pole with trained agent.

**4 Screenshots**
![grafik](https://user-images.githubusercontent.com/79243976/216291426-70bc29cb-caf2-4900-935b-b6ee7e362e91.png)

**5 Additional Informations**

Python version 3.10.9

5.1 Operating System
   - [ ] Linux
   - [X] Windows
   - [ ] Mac OS

**Comment by rizkydiprasetya** [comment]
CI test looks fine. Probably your local encvironment.

**Comment by detlefarend** [comment]
Did you run it locally?

**Comment by rizkydiprasetya** [comment]
works.

**Comment by detlefarend** [comment]
On my ubuntu machine under python 3.10.6, it also runs. Weird...

However, can we improve the howto to a straightforward success story? The policy seems to perform and solve the problem. But after reloading the model, the next run directly fails...

**Comment by rizkydiprasetya** [comment]
Works on my windows. So, check your dependencies again. I have created those list last couple of weeks, better to use it.

I will check that.

**Comment by detlefarend** [comment]
Okay, that's good. Thanks for checking!
