### ISSUE TITLE
BF-Systems: New Sample "Cart-Pole"

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#639]
The cart-pole problem shall be implemented as a MuJoCo sample system.

A draft mjcf file is already placed under mlpro/bf/systems/pool and just needs to be validated/improved...

Tasks:

- [x] BF-Systems: Howto to demonstrate/validate the system
- [x] RL: Howto to solve the problem by training an agent (copy/modify howto_rl_agent_005)

**Comment by detlefarend** [comment]
Hi @rizkydiprasetya, could you take over this issue? If not, then assign it to me...

Btw: the mjcf file was generated by chatGPT...

**Comment by rizkydiprasetya** [comment]
ok

**Comment by rizkydiprasetya** [comment]
@detlefarend Problem on defining discrete action space, because the action space is autodetected from xml file which is a continuous space. I couldnt proceed with the RL, unless I can change the predefined action space from the xml generated action space.

**Comment by detlefarend** [comment]
I didn't understand the problem. In my thinking an action space has dimensions. Can we extract these dimensions from the xml file? I saw that there is a special node.

**Comment by rizkydiprasetya** [comment]
The problem is, the extracted action space from xml is a continuous space not a discrete space. Which node are you talking about?

**Comment by detlefarend** [comment]
Please put it on the agenda for our next meeting.

**Comment by detlefarend** [comment]
And to answer your question: I mean node <actuator>.

**Comment by rizkydiprasetya** [comment]
Actuator is continuous space...

**Comment by detlefarend** [comment]
Means what? What will not work?

**Comment by rizkydiprasetya** [comment]
CartPole is a discrete action, where either max torque or -max torque. So this is either 0 or 1 (discrete). But MuJoCo you control the range value between -max torque until max torque (continuous). This is what I meant.

**Comment by detlefarend** [comment]
Ok, that means that we can't define the origin cart pole problem in MuJoCo directly? In thst case we have a similar but different env that is also an interesting pool object.

Origin cartpole can be implemented by a wrapping env class that accepts discrete actions and maps it to -50, 50.

It would be cool to have both.

**Comment by rizkydiprasetya** [comment]
@detlefarend done. Both implemented. Thanks for the hints. You could check it on our quality branch. Howto RL Agent 006.
