### ISSUE TITLE
BF-ML: Class Model - Extensions for evaluation

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#642]
**Description/Motivation**
As discussed in #620, some extensions for defining an objective for evaluation during training are needed:

![2023-02-23_10-27](https://user-images.githubusercontent.com/79243976/220868659-6f4400ee-3d1e-4b5a-a1ed-5605062298c2.png)

**Task list**
- [x] 1. Review: relation to method get_accuracy()
- [ ] 2. Add new methods as discussed

**Related issues**
#620

**Cross references**
...

**Comment by detlefarend** [comment]
Hi @steveyuwono, could you take over this issue? I think, task 2 is worth to discuss. I put it on the agenda for our next meeting...

**Comment by steveyuwono** [comment]
> Hi @steveyuwono, could you take over this issue? I think, task 2 is worth to discuss. I put it on the agenda for our next meeting...

Okay, sure. We can discuss this tomorrow

**Comment by detlefarend** [comment]
Today we decided that new methods evaluate() are redundant. We will rather use the existing method get_accuracy() as basis for online adaptive training. We also decided to add a new custom method _get_accuracy().
