### ISSUE TITLE
RTD: MuJoCo-based Systems

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#647]
**Description/Motivation**
After review, here are some proposals to improve the documentation for the MuJoCo integration.

**Task list**
- [x] 1. Having an eye-catching gif on top of the documentation would be nice.
- [x] 2. Cross references to helpful tools to view and edit a MuJoCo system

**Related issues**
#...

**Cross references**
...

**Comment by rizkydiprasetya** [comment]
![mujoco_cartpole](https://user-images.githubusercontent.com/75730306/223546108-5e7b1992-5e80-4ddb-85d1-58b20c380309.gif)
for point number 1
