### ISSUE TITLE
RL: HowTo about train and reload single agent in MBRL

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#655]
**Description/Motivation**
Provide a success story of MBRL to train and reload the single agent, similar to **howto_rl_agent_005_train_and_reload_single_agent.py** or **howto_rl_agent_011_train_and_reload_single_agent_gym.py**.

**Task list**
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#...

**Cross references**
https://github.com/fhswf/MLPro/blob/supervised_learning1/src/mlpro/rl/examples/howto_rl_agent_005_train_and_reload_single_agent.py

**Comment by steveyuwono** [comment]
Hi @detlefarend , following the new draft you introduced **howto_rl_mb_001_train_and_reload_model_based_agent_gym.py**, I replaced the numbering to 003 because 001 and 002 are used.

We have a little problem with the gym environment in MBRL. In our wrapper, the reward computation of a gym environment is executed during **simulate_reaction** because the gym environment calculates it. Then the reward is stored in a variable namely **self._last_reward**, which is used in **compute_reward**.
![image](https://user-images.githubusercontent.com/88610818/223704930-0e210d7d-e213-46a2-8e03-3bad4e5e7c13.png)
![image](https://user-images.githubusercontent.com/88610818/223704523-1a1a1ea7-af96-4bae-9c49-28a2eb3c23fe.png)

Meanwhile, in MBRL, we have basically three options for **EnvModel**: 1) set an adaptive reward function, 2) set up a reward function manually, and 3) copy the reward function from the environment. For the gym environment, it is not possible to use Approach 3 because it will return an empty variable of **self._last_reward**. While setting up its own reward function as in Approach 2 might have different output from its native reward function from the gym environment, since the input is limited only to previous states and current states. This is not always the case in every gym environment.

But anyway. at the moment, the howto is running but the reward value returns always 0. I will rethink this again tomorrow and inform you if there are any updates. Thank you!

**Comment by detlefarend** [comment]
Hi @steveyuwono, I just reviewed the howto mb 003. I think there is a little left to do:

- I guess, there is still a misunderstanding due to the hyperparameters. Let's talk about this tomorrow.
- It logs even in backend mode
- It currently raises an error at the end of runtime
