### ISSUE TITLE
Meeting: Workshop 31.3.2023

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#658]
**Before the meeting**
- [ ] Agenda prepared
- [x] Room or Zoom prepared
- [x] Attendees invited

**Agenda**
1. Docker

**Preparation**
...

**Related issues**
...

**After the meeting**
- [ ] Decisions documented
- [ ] Next steps defined

**Comment by detlefarend** [comment]
Hi everyone, feel free to add other topics to the agenda.

**Comment by detlefarend** [comment]
@rizkydiprasetya, could we get in touch with docker after releasing v1?

**Comment by detlefarend** [comment]
Postponed due to my illnes...

**Comment by rizkydiprasetya** [comment]
Ok, I could give some introduction to it.
