### ISSUE TITLE
Bug: Howtos for MBRL fail after installing MLPro from pip  

### ISSUE THREAD

**Issue by laxmikantbaheti** [fhswf/MLPro#666]
**1 Describe the bug**

**2 To Reproduce**
1. Install latest mlpro version from pip
2. Run the howto.rl.mb.001 and 002

**3 Expected behavior**
...

**4 Screenshots**
![image](https://user-images.githubusercontent.com/100450659/224723807-ef5015cf-8145-45d4-a9df-a2edb50ae166.png)

**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [x] Windows
   - [ ] Mac OS

**Comment by steveyuwono** [comment]
Hi @laxmikantbaheti , thank you for letting us know. I just checked it and got the same problem. This happens because the **pytorch** folder in mlpro.sl.pool.afct.fnn is somehow missing after installing through pip, although the file is actually there in our GitHub repo.
![image](https://user-images.githubusercontent.com/88610818/224747755-d68b3f37-4315-4690-b550-1153dc8e38c9.png)
![image](https://user-images.githubusercontent.com/88610818/224748075-a50742bf-cf99-44ce-9d28-e5b3f5a606bd.png)

**Comment by rizkydiprasetya** [comment]
As far as I know you need to put __init__.py on that folder, so it will be detected as python module by the Python Builder

**Comment by detlefarend** [comment]
Same problem under Linux...

@steveyuwono: I assume that the reason is the missing __init__.py in folder pytorch. Without this file it's only a folder and not a sub-package... It's odd, that everything is fine if you install from the local src folder.

**Comment by detlefarend** [comment]
Proposal: let's add the init file and install from the github branch.

**Comment by rizkydiprasetya** [comment]
@detlefarend because pypi will build first the package and recursively detect the module by `__init__.py`. For non python module, you can put it on file "MANIFEST.in" to be included in the installation package. For local, it will just linked the installation to the local folder.

**Comment by steveyuwono** [comment]
Okay, I'll update

**Comment by detlefarend** [comment]
@rizkydiprasetya   @steveyuwono @laxmikantbaheti I think it's not necessary to create a bugfix release for it. Let's collect some issues first. We also have a persistence gap (#664) to solve before the mbrl howtos are running properly.

**Comment by steveyuwono** [comment]
> @rizkydiprasetya @steveyuwono @laxmikantbaheti I think it's not necessary to create a bugfix release for it. Let's collect some issues first. We also have a persistence gap (#664) to solve before the mbrl howtos are running properly.

It is solved by adding __init__. Okay, agree. Then, I will close this issue.
