### ISSUE TITLE
Refact: PyTorch Implementation of SL FFN - Conversion numpy/tensor

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#705]
**Motivation**
Hi Steve, I got this warning during rtd code processing. It seems that there is a potential performance lack in the FNN/Torch implementation. Could you please check it? Thx!

![grafik](https://user-images.githubusercontent.com/79243976/230765475-f6423926-da27-4901-a38d-5692844619ea.png)

**Benefit**
Better performance.

**Are the proposed changes backward compatible?** 
- [ ] Yes
- [ ] No

**Related development objects**
- [ ] ...

**Comment by steveyuwono** [comment]
Hi Detlef, thank you for noticing this. This has been solved and merged into the main.
