### ISSUE TITLE
OA-Tasks: Template Classes for Classification

### ISSUE THREAD

**Issue by steveyuwono** [fhswf/MLPro#751]
**Description/Motivation**
A template class for classification, which will be similar to ClusterAnalyzer and Cluster template class, e.g.
- get_cluster_membership() -> get_class_membership()
- get_membership() -> .......
 

**Task list**
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#...

**Cross references**
...

**Comment by detlefarend** [comment]
To be discussed...
