### ISSUE TITLE
WR: New wrapper class for River cluster algorithm DBScan

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#771]
**Description/Motivation**
...

**Task list**
- [ ] 1. Do this
- [ ] 2. Do that

**Related issues**
#...

**Cross references**
...

**Comment by detlefarend** [comment]
@steveyuwono Could I please ask you to take over this implementation? Thank you very much!

**Comment by steveyuwono** [comment]
> @steveyuwono Could I please ask you to take over this implementation? Thank you very much!

Hi @detlefarend, do you mean the native algorithm of DBScan? DenStream and DBSTREAM are the two variants that utilize DBScan to connect microclusters. I don't think that they have a template class for DBScan that can be wrapped. Or I might be mistaken.

**Comment by detlefarend** [comment]
@syam47 I am not sure any more, why we need this algorithm. Maybe I misunderstood something last Friday. Can you give us a hint about this? Thx!

**Comment by syam47** [comment]
Sorry Detlef. DBScan algorithm is not in River. I needed the algorithm because its the most used clustering algorithm for AD. I am not sure about Denstream and Dbstream. DBScan algorithm is found in ScikitLearn.

**Comment by detlefarend** [comment]
Ok, but you don't want to re-implement existing AD algorithms, right? You want to implement own AD derivates that analyze/observe centroid-based clusters. Here we already have a list of wrapped cluster analyzers. So I guess we don't need another one or is it elementary for you to have DBScan from scikit-learn?
