### ISSUE TITLE
Pending MLPro-Extension "fhswf/mt_baheti"

### ISSUE THREAD

**Issue by mlpro-admin** [fhswf/MLPro#870]
A new extension for MLPro has been detected. Please check for plausibility and add the repo to the whitelist or blacklist of the MLPro extension hub.

| | |
|-|-|
|**Title**|mt_baheti|
|**URL**|https://github.com/fhswf/mt_baheti|
|**Version**|v1.0.0|
|**Topics**|mlpro-extension|
|**Description**|This repository is a part of master's thesis by Laxmikant Shrikant Baheti as a part of course Systems Engineering and Engineering Management|

**Checklist:**
- [x] **Plausibility check**
   - [x] Repo is no malware (mass generated pseudo-repo, dummy without senseful content, spam, ...)
   - [x] Repo has a concrete relation to MLPro 
   - [x] Repo fulfills minimum quality requirements (documenation, sample files, ...) 
- [x] **Repo has been whitelisted**
- [ ] **Repo has been blacklisted**
   - [ ] The reasons for this decision were commented in this issue

**Comment by mlpro-admin** [comment]
@laxmikantbaheti: 
Dear Ladies and Gentlemen, 

thank you for wanting to contribute to the MLPro extension hub with your repository [fhswf/mt_baheti](https://github.com/fhswf/mt_baheti). We subject the extension to a short plausibility check and then release it for the extension hub. We will keep you updated on this in this issue. If you have any questions or comments, please feel free to contact us here at any time in the chat. 

If you do not want your repository to be listed in the MLPro extension hub, please let us know as soon as possible and remove the _mlpro-extension_ topic. If you just want to delay the entry to the extension hub, please also contact us. In this case, we will blacklist your repository until you tell us to whitelist it.

Kind regards,
Your MLPro Team

**Comment by detlefarend** [comment]
@laxmikantbaheti: Thank you for your contribution! Your repository has been whitelisted and will appear tomorrow in the extension hub.
