### ISSUE TITLE
OA: Time stamp of an anomaly

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#880]
In #876 class bf.events.Event has been extended by an optional time stamp. In the special case of an anomaly event the time stamp shall be set to that of the causing instance. To ensure this a new method AnomalyDetector._raise_anomaly() is proposed. It has all parameters of method _raise_event() plus parameter p_inst:Instance for the causing instance. The method sets the time stamp of the event to that of the instance and calls method _raise_event().

**Comment by detlefarend** [comment]
Hi @syamrajsatheesh, with regards to our discussion about anomaly prediction it would be cool to implement this little piece of logic. Let me know if something is not clear. Thank you!

**Comment by syamrajsatheesh** [comment]
I will work on it Detlef...
