### ISSUE TITLE
Admin: Frequent scheduling of unit test workflows (all MLPro repos)

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#910]
**Description/Motivation**
The unit test workflow shall be executed frequently (e.g. weekly/monthly) to determine incompatible changes of 3rd party packages.

**Task list**
- [x] 1. Cron statement in the ci.yaml file

**Comment by detlefarend** [comment]
@steveyuwono @laxmikantbaheti: all repos MLPro, MLPro-Int-* run now an automatic weekly unit test (Monday 1am). Furthermore, unit tests can now be run manually.

**Comment by steveyuwono** [comment]
> @steveyuwono @laxmikantbaheti: all repos MLPro, MLPro-Int-* run now an automatic weekly unit test (Monday 1am). Furthermore, unit tests can now be run manually.

Super!
