### ISSUE TITLE
Refact: New Repo for MuJoCo

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#939]
**Motivation**
The wrapper code and related howto files of 3rd party package MuJoCo shall be relocated to a new repository to prevent MLPro from incompatible changes.

**Benefit**
-  MLPro stays stable
-  3rd party support becomes optional
-  3rd party support packages will be listed in the MLPro extension hub

**Are the proposed changes backward compatible?**
- [ ] Yes
- [ ] No

**To do**
- [x] Creation of new repository MLPro-Int-MuJoCo (template: [MLPro-Extension](https://github.com/fhswf/MLPro-Extension))
- [x] Relocation of related wrapper code and howto files to new repository
- [x] Relocation of related documentation to new repository
- [ ] Preparation for MLPro 1.4.x without MuJoCo
- [ ] Release MLPro-Int-MuJoCo 1.0.0
- [x] Whitelist MLPro-Int-MuJoCo in MLPro-Extension
- [ ] Update MLPro-Int-SB3 plus related howtos

**Branch**
wrappers/relocation2

**See also**
https://github.com/fhswf/MLPro/wiki/30-MLPro-Extension

**Comment by steveyuwono** [comment]
Hi @detlefarend, just reviewed this, I have a question regarding the integration. It is clear that the **_mlpro.wrappers.mujoco_** codes are going to be moved into the new repository. However, in the **_mlpro.bf.systems_** module, we have a **_System_** class that can be configured to work with a Mujoco file. In such cases, we need to initialize the wrapper if it is called, [as shown in this link](https://github.com/fhswf/MLPro/blob/56b1beb4b69e1dd58f16d44f7a56f541ef4869d5/src/mlpro/bf/systems/basics.py#L1168-L1169) Then, this also affects the **_EnvBase_** class in **_mlpro.rl.models_env_**. Should these integrations also be removed from MLPro, and updated **_System_** and **_EnvBase_** classes be created within the wrapper?

**Comment by detlefarend** [comment]
> Hi [@detlefarend](https://github.com/detlefarend), just reviewed this, I have a question regarding the integration. It is clear that the **_mlpro.wrappers.mujoco_** codes are going to be moved into the new repository. However, in the **_mlpro.bf.systems_** module, we have a **_System_** class that can be configured to work with a Mujoco file. In such cases, we need to initialize the wrapper if it is called, [as shown in this link](https://github.com/fhswf/MLPro/blob/56b1beb4b69e1dd58f16d44f7a56f541ef4869d5/src/mlpro/bf/systems/basics.py#L1168-L1169) Then, this also affects the **_EnvBase_** class in **_mlpro.rl.models_env_**. Should these integrations also be removed from MLPro, and updated **_System_** and **_EnvBase_** classes be created within the wrapper?

Hi @steveyuwono, I also checked the code. The design doesn't follow our usual wrapper concept, but it encapsulates the optional MuJoCo parts suitable. It should be enough to redirect the wrapper access in ll 1169, 1259 to mlpro_int_mujoco. The only idea I have to improve something is to embed the imports in a try/except statement with an error log that points out the need for installing our MuJoCo extension.

**Comment by steveyuwono** [comment]
> > Hi [@detlefarend](https://github.com/detlefarend), just reviewed this, I have a question regarding the integration. It is clear that the **_mlpro.wrappers.mujoco_** codes are going to be moved into the new repository. However, in the **_mlpro.bf.systems_** module, we have a **_System_** class that can be configured to work with a Mujoco file. In such cases, we need to initialize the wrapper if it is called, [as shown in this link](https://github.com/fhswf/MLPro/blob/56b1beb4b69e1dd58f16d44f7a56f541ef4869d5/src/mlpro/bf/systems/basics.py#L1168-L1169) Then, this also affects the **_EnvBase_** class in **_mlpro.rl.models_env_**. Should these integrations also be removed from MLPro, and updated **_System_** and **_EnvBase_** classes be created within the wrapper?
> 
> Hi @steveyuwono, I also checked the code. The design doesn't follow our usual wrapper concept, but it encapsulates the optional MuJoCo parts suitable. It should be enough to redirect the wrapper access in ll 1169, 1259 to mlpro_int_mujoco. The only idea I have to improve something is to embed the imports in a try/except statement with an error log that points out the need for installing our MuJoCo extension.

Hi @detlefarend , okay, well noted. Thank you for the information.
