### ISSUE TITLE
Refact: Class StreamMLProPOutliers - New parameter p_outlier_rate

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#948]
Parameter p_outlier_frequency shall be replaced by a new parameter p_outlier_rate:

![PXL_20240426_142352170 MP](https://github.com/fhswf/MLPro/assets/79243976/58ade54f-5b2b-4e1c-b9ce-a510ee3bc4ca)

**Motivation**
...

**Benefit**
...

**Are the proposed changes backward compatible?** 
- [ ] Yes
- [ ] No

**Related development objects**
- [ ] ...

**Comment by detlefarend** [comment]
Hi @steveyuwono @syamrajsatheesh, this is done and already merged to main.

**Comment by steveyuwono** [comment]
> Hi @steveyuwono @syamrajsatheesh, this is done and already merged to main.

Hi @detlefarend , perfect!!
