### ISSUE TITLE
Bug: howto_bf_streams_011_native_stream_ClusterbasedAnomalies.py doesn't run under Python 3.12

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#985]
**1 Describe the bug**
Since adding Python 3.12 to MLPro's unit test the above howto throws an error. 

**2 To Reproduce**
1. Install Python 3.12 
2. Run the above howto

**3 Expected behavior**
The howto should run without any exception.

**4 Screenshots**
![2024-05-19_15-58](https://github.com/fhswf/MLPro/assets/79243976/48d6d577-0a6a-49eb-bc98-3704accb08fa)

**5 Additional Informations**

5.1 Operating System
   - [x] Linux
   - [x] Windows
   - [x] Mac OS

**Comment by syamrajsatheesh** [comment]
This was a minor bug in the code. I fixed it.

**Comment by detlefarend** [comment]
> This was a minor bug in the code. I fixed it.

This will probably collide with my ongoing refactoring changes. See slack.
