### ISSUE TITLE
Bug: Outdated Example

### ISSUE THREAD

**Issue by hsdwolfo** [fhswf/MLPro#991]
- MLPro/experiments/Issue 312 - RL Solution for the Double Pendulum/DP_002_DDPG.py is outdated.
  - Line 26-27 wrappers moved to mlpro_int_sb3.wrappers and likewise mlpro_int_gymnasium.wrappers

- Env error in package "mlpro/rl/pool/envs/doublependulum.py"
  - line 461: state_new[3] = 0  # index 4 was out of range 
  - line 467: state_old[3] = 0  # index 4 was out of range

**Comment by detlefarend** [comment]
@hsdwolfo This folder is not part of the public documentation. Please ignore or solve #312:)
