### ISSUE TITLE
Bug: Normalizer Z-Trans needs to be reviewed

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#993]
**1 Describe the bug**
- **Class bf.math.normalizers.NormalizerZTrans**
    - Method update_parameters() is not prepared for just remove a single data entity. If just p_data_del is filled an error is raised.
    - Method update_parameters(): equations are hard to recap and maybe wrong   
                

**2 To Reproduce**

**3 Expected behavior**

**4 Screenshots**

**5 Additional Informations**
5.1 Operating System
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac OS

5.2 Branch
bf/oa/streams/refact

**6 References**
http://datagenetics.com/blog/november22017/index.html

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend I am working on this. I will give u update

**Comment by laxmikantbaheti** [comment]
@detlefarend , just a short update, the version of z transformation works perfect for both new and deleted data. I need to verify changes after that. I am on it...

**Comment by laxmikantbaheti** [comment]
Hi @detlefarend , I have fixed a small bug in the update parameter method. I like how you seperated the method for both cases, new and old data, it will automatically make sure all the possible cases. There was just a small bug in the equation. Now it's fixed, by seeing the howto_bf_math_011. Just needed some fix in the means and std equations. 

To understand the logic of updating parameters on p_data_del:
The calculation of STD for a new value was already correct. i.e. we could calulate `std_new` based on old mean and std.
To update the std on deleted data, we can think of it also as _migrating back from the std of dataset with added data to the one without the new data (the new data is basically data_del in this case)_. And then just solve the equation.

Let me know whenever you are able to take a look.
