### ISSUE TITLE
OA: Addition of further cluster properties

### ISSUE THREAD

**Issue by syamrajsatheesh** [fhswf/MLPro#994]
**Description/Motivation**
...

**Task list**
- [x] 1. New properties to clusters
    - [x] Center
    - [x] Density
    - [x] Geometric size
    - [x] Compactness 

**Related issues**
#...

**Cross references**
...

**Cross references**
...

**Comment by detlefarend** [comment]
Hi @syamrajsatheesh, fyi: I added labels 'OA' and 'next release' and removed the version. We set the version at release time.

**Comment by syamrajsatheesh** [comment]
> Hi @syamrajsatheesh, fyi: I added labels 'OA' and 'next release' and removed the version. We set the version at release time.

Ok Detlef.
