### ISSUE TITLE
Bug: OA.Streams.Tasks.ClusterAnalyzer - Typo in method new_cluster_allowed()

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro#998]
**1 Describe the bug**

**2 To Reproduce**

**3 Expected behavior**

**4 Screenshots**

**5 Additional Informations**

5.1 Operating System
   - [ ] Linux
   - [ ] Windows
   - [ ] Mac OS

**Comment by detlefarend** [comment]
@syamrajsatheesh fyi: there's a typo in this method. It is already fixed but not yet merged to main. Let me know if you need the correction.

**Comment by syamrajsatheesh** [comment]
OK Detlef.
